export const UPDATE = 'user/UPDATE'
export const ADD = 'user/ADD'
export const REMOVE = 'user/REMOVE'

export const GET_INFO = 'user/GET_INFO'
export const GET_INFO_COMPLETED = 'user/GET_INFO_COMPLETED'
export const GET_INFO_FAILED = 'user/GET_INFO_FAILED'

export const UPDATE_INFO = 'user/UPDATE_INFO'
export const UPDATE_INFO_COMPLETED = 'user/UPDATE_INFO_COMPLETED'
export const UPDATE_INFO_FAILED = 'user/UPDATE_INFO_FAILED'

export const CHANGE_NOTIFY_STATUS = 'user/CHANGE_NOTIFY_STATUS'
export const CHANGE_NOTIFY_STATUS_COMPLETED = 'user/CHANGE_NOTIFY_STATUS_COMPLETED'
export const CHANGE_NOTIFY_STATUS_FAILED = 'user/CHANGE_NOTIFY_STATUS_FAILED'

export const UPDATE_AVATAR = 'user/UPDATE_AVATAR'
export const UPDATE_AVATAR_COMPLETED = 'user/UPDATE_AVATAR_COMPLETED'
export const UPDATE_AVATAR_FAILED = 'user/UPDATE_AVATAR_FAILED'

export const UPDATE_LOCAL_AVATAR = 'user/UPDATE_LOCAL_AVATAR'

export const SET_USER_INFO = 'user/SET_USER_INFO'
