export const GET_SERVICE_LIST = 'product/GET_SERVICE_LIST'
export const GET_SERVICE_LIST_COMPLETED = 'product/GET_SERVICE_LIST_COMPLETED'
export const GET_SERVICE_LIST_FAILED = 'product/GET_SERVICE_LIST_FAILED'

export const GET_SERVICE_LIST_TC = 'product/GET_SERVICE_LIST_TC'
export const GET_SERVICE_LIST_TC_COMPLETED = 'product/GET_SERVICE_LIST_TC_COMPLETED'
export const GET_SERVICE_LIST_TC_FAILED = 'product/GET_SERVICE_LIST_TC_FAILED'

export const GET_BILL_ALIAS = 'product/GET_BILL_ALIAS'
export const GET_BILL_ALIAS_COMPLETED = 'product/GET_BILL_ALIAS_COMPLETED'
export const GET_BILL_ALIAS_FAILED = 'product/GET_BILL_ALIAS_FAILED'

export const GET_ACCOUNT = 'product/GET_ACCOUNT'
export const GET_ACCOUNT_COMPLETED = 'product/GET_ACCOUNT_COMPLETED'
export const GET_ACCOUNT_FAILED = 'product/GET_ACCOUNT_FAILED'

export const GET_CHECK_BILL = 'product/GET_CHECK_BILL'
export const GET_CHECK_BILL_COMPLETED = 'product/GET_CHECK_BILL_COMPLETED'
export const GET_CHECK_BILL_FAILED = 'product/GET_CHECK_BILL_FAILED'

export const CHECK_PAY_BILL = 'product/CHECK_PAY_BILL'
export const CHECK_PAY_BILL_COMPLETED = 'product/CHECK_PAY_BILL_COMPLETED'
export const CHECK_PAY_BILL_FAILED = 'product/CHECK_PAY_BILL_FAILED'

export const SET_CHECK_BILL = 'product/SET_CHECK_BILL'

export const SEND_OTP = 'product/SEND_OTP'
export const SEND_OTP_COMPLETED = 'product/SEND_OTP_COMPLETED'
export const SEND_OTP_FAILED = 'product/SEND_OTP_FAILED'

export const SEND_OTP_RECHARGE = 'product/SEND_OTP_RECHARGE'
export const SEND_OTP_RECHARGE_COMPLETED = 'product/SEND_OTP_RECHARGE_COMPLETED'
export const SEND_OTP_RECHARGE_FAILED = 'product/SEND_OTP_RECHARGE_FAILED'

export const COMPLETE_RECHARGE = 'product/COMPLETE_RECHARGE'
export const COMPLETE_RECHARGE_COMPLETED = 'product/COMPLETE_RECHARGE_COMPLETED'
export const COMPLETE_RECHARGE_FAILED = 'product/COMPLETE_RECHARGE_FAILED'

export const SET_SEND_OTP = 'product/SET_SEND_OTP'
export const SET_SEND_OTP_RECHARGE = 'product/SET_SEND_OTP_RECHARGE'
export const SET_COMPLETE_RECHARGE = 'product/SET_COMPLETE_RECHARGE'
export const SET_CHECK_PAY_BILL = 'product/SET_CHECK_PAY_BILL'

export const GET_DATA_HISTORY_BILL_PAYMENT = 'product/GET_DATA_HISTORY_BILL_PAYMENT'
export const GET_DATA_HISTORY_BILL_PAYMENT_COMPLETED = 'product/GET_DATA_HISTORY_BILL_PAYMENT_COMPLETED'
export const GET_DATA_HISTORY_BILL_PAYMENT_FAILED = 'product/GET_DATA_HISTORY_BILL_PAYMENT_FAILED'

export const GET_BENEFIT_NAME_API_CARD = 'product/GET_BENEFIT_NAME_API_CARD'
export const GET_BENEFIT_NAME_API_CARD_COMPLETED = 'product/GET_BENEFIT_NAME_API_CARD_COMPLETED'
export const GET_BENEFIT_NAME_API_CARD_FAILED = 'product/GET_BENEFIT_NAME_API_CARD_FAILED'

export const SEND_OTP_PREPAID_CARD = 'product/SEND_OTP_PREPAID_CARD'
export const SEND_OTP_PREPAID_CARD_COMPLETED = 'product/SEND_OTP_PREPAID_CARD_COMPLETED'
export const SEND_OTP_PREPAID_CARD_FAILED = 'product/SEND_OTP_PREPAID_CARD_FAILED'

export const SET_PRODUCT = 'product/SET_PRODUCT'

export const GET_DATA_QUERY_SCHEDULE_BILL = 'product/GET_DATA_QUERY_SCHEDULE_BILL'
export const GET_DATA_QUERY_SCHEDULE_BILL_COMPLETED = 'product/GET_DATA_QUERY_SCHEDULE_BILL_COMPLETED'
export const GET_DATA_QUERY_SCHEDULE_BILL_FAILED = 'product/GET_DATA_QUERY_SCHEDULE_BILL_FAILED'

export const GET_DATA_QUERY_SCHEDULE_HISTORY = 'product/GET_DATA_QUERY_SCHEDULE_HISTORY'
export const GET_DATA_QUERY_SCHEDULE_HISTORY_COMPLETED = 'product/GET_DATA_QUERY_SCHEDULE_HISTORY_COMPLETED'
export const GET_DATA_QUERY_SCHEDULE_HISTORY_FAILED = 'product/GET_DATA_QUERY_SCHEDULE_HISTORY_FAILED'

export const DELETE_HISTORY_SERVICE = 'product/DELETE_HISTORY_SERVICE'
export const DELETE_HISTORY_SERVICE_COMPLETED = 'product/DELETE_HISTORY_SERVICE_COMPLETED'
export const DELETE_HISTORY_SERVICE_FAILED = 'product/DELETE_HISTORY_SERVICE_FAILED'

export const PAYMENT_SEND_EMAIL = 'product/PAYMENT_SEND_EMAIL'
export const PAYMENT_SEND_EMAIL_COMPLETED = 'product/PAYMENT_SEND_EMAIL_COMPLETED'
export const PAYMENT_SEND_EMAIL_FAILED = 'product/PAYMENT_SEND_EMAIL_FAILED'

export const RECHARGE_SEND_EMAIL = 'product/RECHARGE_SEND_EMAIL'
export const RECHARGE_SEND_EMAIL_COMPLETED = 'product/RECHARGE_SEND_EMAIL_COMPLETED'
export const RECHARGE_SEND_EMAIL_FAILED = 'product/RECHARGE_SEND_EMAIL_FAILED'

export const MAKE_TRANSACTION_BILLING = 'product/MAKE_TRANSACTION_BILLING'
export const MAKE_TRANSACTION_BILLING_COMPLETED = 'product/MAKE_TRANSACTION_BILLING_COMPLETED'
export const MAKE_TRANSACTION_BILLING_FAILED = 'product/MAKE_TRANSACTION_BILLING_FAILED'

export const SEND_OTP_BILLING = 'product/SEND_OTP_BILLING'
export const SEND_OTP_BILLING_COMPLETED = 'product/SEND_OTP_BILLING_COMPLETED'
export const SEND_OTP_BILLING_FAILED = 'product/SEND_OTP_BILLING_FAILED'

export const DELETE_AUTO_BILLING = 'product/DELETE_AUTO_BILLING'
export const DELETE_AUTO_BILLING_COMPLETED = 'product/DELETE_AUTO_BILLING_COMPLETED'
export const DELETE_AUTO_BILLING_FAILED = 'product/DELETE_AUTO_BILLING_FAILED'

export const SET_SCHEDULE_RECHARGE = 'product/SET_SCHEDULE_RECHARGE'

export const SET_IS_NOW = 'product/SET_IS_NOW'
