export const GET_ACCOUNT = 'account/GET_ACCOUNT'
export const GET_ACCOUNT_COMPLETED = 'account/GET_ACCOUNT_COMPLETED'
export const GET_ACCOUNT_FAILED = 'account/GET_ACCOUNT_FAILED'

export const GET_CARD = 'account/GET_CARD'
export const GET_CARD_COMPLETED = 'account/GET_CARD_COMPLETED'
export const GET_CARD_FAILED = 'account/GET_CARD_FAILED'

export const GET_CARD_FULL = 'account/GET_CARD_FULL'
export const GET_CARD_FULL_COMPLETED = 'account/GET_CARD_FULL_COMPLETED'
export const GET_CARD_FULL_FAILED = 'account/GET_CARD_FULL_FAILED'

export const CARD_CHANGE_STATUS = 'account/CARD_CHANGE_STATUS'
export const CARD_CHANGE_STATUS_COMPLETED = 'account/CARD_CHANGE_STATUS_COMPLETED'
export const CARD_CHANGE_STATUS_FAILED = 'account/CARD_CHANGE_STATUS_FAILED'
export const RESET_CARD_CHANGE_STATUS = 'account/RESET_CARD_CHANGE_STATUS'

export const MAKE_TRANSACTION_ACCOUNT = 'account/MAKE_TRANSACTION_ACCOUNT'
export const MAKE_TRANSACTION_ACCOUNT_COMPLETED = 'account/MAKE_TRANSACTION_ACCOUNT_COMPLETED'
export const MAKE_TRANSACTION_ACCOUNT_FAILED = 'account/MAKE_TRANSACTION_ACCOUNT_FAILED'

export const SEND_OTP = 'account/SEND_OTP'
export const SEND_OTP_COMPLETED = 'account/SEND_OTP_COMPLETED'
export const SEND_OTP_FAILED = 'account/SEND_OTP_FAILED'

export const RESET_STORE = 'account/RESET_STORE'

export const GET_LIST_SAVE_ACCOUNT = 'account/GET_LIST_SAVE_ACCOUNT'
export const GET_LIST_SAVE_ACCOUNT_COMPLETED = 'account/GET_LIST_SAVE_ACCOUNT_COMPLETED'
export const GET_LIST_SAVE_ACCOUNT_FAILED = 'account/GET_LIST_SAVE_ACCOUNT_FAILED'

export const HISTORY_BY_ACCOUNT = 'account/HISTORY_BY_ACCOUNT'
export const HISTORY_BY_ACCOUNT_COMPLETED = 'account/HISTORY_BY_ACCOUNT_COMPLETED'
export const HISTORY_BY_ACCOUNT_FAILED = 'account/GET_LIST_SAVE_ACCOUNT_FAILED'

export const GET_CONTRACT_BALANCE = 'account/GET_CONTRACT_BALANCE'
export const GET_CONTRACT_BALANCE_COMPLETED = 'account/GET_CONTRACT_BALANCE_COMPLETED'
export const GET_CONTRACT_BALANCE_FAILED = 'account/GET_CONTRACT_BALANCE_FAILED'

export const CARD_PAY_API = 'account/CARD_PAY_API'
export const CARD_PAY_API_COMPLETED = 'account/CARD_PAY_API_COMPLETED'
export const CARD_PAY_API_FAILED = 'account/CARD_PAY_API_FAILED'

export const CARD_PRE_PAY_API = 'account/CARD_PRE_PAY_API'
export const CARD_PRE_PAY_API_COMPLETED = 'account/CARD_PRE_PAY_API_COMPLETED'
export const CARD_PRE_PAY_API_FAILED = 'account/CARD_PRE_PAY_API_FAILED'

export const PASSED_CARD_CURRENT_ACCOUNT_SELECT = 'account/PASSED_CARD_CURRENT_ACCOUNT_SELECT'
export const PASSED_CARD_CURRENT_CONTRACT_NUMBER = 'account/PASSED_CARD_CURRENT_CONTRACT_NUMBER'
export const PASSED_CARD_INPUT_AMOUNT_PAY = 'account/PASSED_CARD_INPUT_AMOUNT_PAY'

export const CHECK_CARD_NAME = 'account/CHECK_CARD_NAME'
export const CHECK_CARD_NAME_COMPLETED = 'account/CHECK_CARD_NAME_COMPLETED'
export const CHECK_CARD_NAME_FAILED = 'account/CHECK_CARD_NAME_FAILED'

export const ADVANCED_SEARCH = 'account/ADVANCED_SEARCH'
export const ADVANCED_SEARCH_COMPLETED = 'account/ADVANCED_SEARCH_COMPLETED'
export const ADVANCED_SEARCH_FAILED = 'account/ADVANCED_SEARCH_FAILED'

export const GET_HISTORY_CREDIT_CARD = 'account/GET_HISTORY_CREDIT_CARD'
export const GET_HISTORY_CREDIT_CARD_COMPLETED = 'account/GET_HISTORY_CREDIT_CARD_COMPLETED'
export const GET_HISTORY_CREDIT_CARD_FAILED = 'account/GET_HISTORY_CREDIT_CARD_FAILED'

export const GET_CA_SA_DETAIL = 'account/GET_CA_SA_DETAIL'
export const GET_CA_SA_DETAIL_COMPLETED = 'account/GET_CA_SA_DETAIL_COMPLETED'
export const GET_CA_SA_DETAIL_FAILED = 'account/GET_CA_SA_DETAIL_FAILED'

export const GET_AMOUNT_STATUS = 'account/GET_AMOUNT_STATUS'
export const GET_AMOUNT_STATUS_COMPLETED = 'account/GET_AMOUNT_STATUS_COMPLETED'
export const GET_AMOUNT_STATUS_FAILED = 'account/GET_AMOUNT_STATUS_FAILED'

export const REDEEM_GET_URL = 'account/REDEEM_GET_URL'
export const REDEEM_GET_URL_COMPLETED = 'account/REDEEM_GET_URL_COMPLETED'
export const REDEEM_GET_URL_FAILED = 'account/REDEEM_GET_URL_FAILED'

export const ACCOUNT_INVESTIGATION = 'account/ACCOUNT_INVESTIGATION'
export const ACCOUNT_INVESTIGATION_COMPLETED = 'account/ACCOUNT_INVESTIGATION_COMPLETED'
export const ACCOUNT_INVESTIGATION_FAILED = 'account/ACCOUNT_INVESTIGATION_FAILED'
export const RESET_ACCOUNT_INVESTIGATION = 'account/RESET_ACCOUNT_INVESTIGATION'

export const MAKE_TRANSACTION_ACCOUNT_ACTIVE_CARD = 'account/MAKE_TRANSACTION_ACCOUNT_ACTIVE_CARD'
export const MAKE_TRANSACTION_ACCOUNT_ACTIVE_CARD_COMPLETED = 'account/MAKE_TRANSACTION_ACCOUNT_ACTIVE_CARD_COMPLETED'
export const MAKE_TRANSACTION_ACCOUNT_ACTIVE_CARD_FAIL = 'account/MAKE_TRANSACTION_ACCOUNT_ACTIVE_CARD_FAIL'

export const SEND_OTP_ACTIVE_CARD = 'account/SEND_OTP_ACTIVE_CARD'
export const SEND_OTP_ACTIVE_CARD_COMPLETED = 'account/SEND_OTP_ACTIVE_CARD_COMPLETED'
export const SEND_OTP_ACTIVE_CARD_FAIL = 'account/SEND_OTP_ACTIVE_CARD_FAIL'

export const CHANGE_STATUS_ACTIVE_CARD = 'account/CHANGE_STATUS_ACTIVE_CARD'
export const CHANGE_STATUS_ACTIVE_CARD_COMPLETED = 'account/CHANGE_STATUS_ACTIVE_CARD_COMPLETED'
export const CHANGE_STATUS_ACTIVE_CARD_FAILED = 'account/CHANGE_STATUS_ACTIVE_CARD_FAILED'

export const SET_ACCOUNT_CARD = 'account/SET_ACCOUNT_CARD'
export const RESET_CARD_ACTIVE_STATUS = 'account/RESET_CARD_ACTIVE_STATUS'
