import {
  sendOTPVerify,
  checkID,
  verifyOTP,
  getResultEkycSdk,
  verifyCustomerInfo,
  reset,
  getTSToken,
  saveAdditionInfo,
  saveLogError,
  getDistrict,
  getSubBranch,
  choiceBranch,
  choiceCombo,
  sendRegister,
  saveReferralCode,
  activeEKYC,
  saveActiveUser,
  reActive,
  checkUsername,
  resetchoicedBranch,
  updateRequestId
} from './actions'

export {
  sendOTPVerify,
  checkID,
  verifyOTP,
  reset,
  getResultEkycSdk,
  verifyCustomerInfo,
  getTSToken,
  saveAdditionInfo,
  saveLogError,
  getDistrict,
  getSubBranch,
  choiceBranch,
  choiceCombo,
  sendRegister,
  saveReferralCode,
  activeEKYC,
  saveActiveUser,
  reActive,
  checkUsername,
  resetchoicedBranch,
  updateRequestId
}
