export const EKYC_SEND_OTP = 'ekyc/EKYC_SEND_OTP'
export const EKYC_SEND_OTP_COMPLETED = 'ekyc/EKYC_SEND_OTP_COMPLETED'
export const EKYC_SEND_OTP_FAILED = 'ekyc/EKYC_SEND_OTP_FAILED'

export const EKYC_VERIFY_OTP = 'ekyc/EKYC_VERIFY_OTP'
export const EKYC_VERIFY_OTP_COMPLETED = 'ekyc/EKYC_VERIFY_OTP_COMPLETED'
export const EKYC_VERIFY_OTP_FAILED = 'ekyc/EKYC_VERIFY_OTP_FAILED'

export const EKYC_CHECK_ID = 'ekyc/EKYC_CHECK_ID'
export const EKYC_CHECK_ID_COMPLETED = 'ekyc/EKYC_CHECK_ID_COMPLETED'
export const EKYC_CHECK_ID_FAILED = 'ekyc/EKYC_CHECK_ID_FAILED'

export const EKYC_RESULT_SDK = 'ekyc/EKYC_RESULT_SDK'

export const VERIFY_CUSTOMER_INFO = 'ekyc/VERIFY_CUSTOMER_INFO'
export const VERIFY_CUSTOMER_INFO_COMPLETED = 'ekyc/VERIFY_CUSTOMER_INFO_COMPLETED'
export const VERIFY_CUSTOMER_INFO_FAILED = 'ekyc/VERIFY_CUSTOMER_INFO_FAILED'

export const GET_TS_TOKEN = 'ekyc/GET_TS_TOKEN'
export const GET_TS_TOKEN_COMPLETED = 'ekyc/GET_TS_TOKEN_COMPLETED'
export const GET_TS_TOKEN_FAILED = 'ekyc/GET_TS_TOKEN_FAILED'

export const CHECK_USER_NAME = 'ekyc/CHECK_USER_NAME'
export const CHECK_USER_NAME_COMPLETED = 'ekyc/CHECK_USER_NAME_COMPLETED'
export const CHECK_USER_NAME_FAILED = 'ekyc/CHECK_USER_NAME_FAILED'
export const RESET_CHECK_USERNAME = 'ekyc/RESET_CHECK_USERNAME'

export const SAVE_ADDITION_INFO = 'ekyc/SAVE_ADDITION_INFO'
export const SAVE_ADDITION_INFO_COMPLETED = 'ekyc/SAVE_ADDITION_INFO_COMPLETED'
export const SAVE_ADDITION_INFO_FAILED = 'ekyc/SAVE_ADDITION_INFO_FAILED'

export const SAVE_LOG = 'ekyc/SAVE_LOG'
export const SAVE_LOG_COMPLETED = 'ekyc/SAVE_LOG_COMPLETED'
export const SAVE_LOG_FAILED = 'ekyc/SAVE_LOG_FAILED'

export const GET_DISTRICT = 'ekyc/GET_DISTRICT'
export const GET_DISTRICT_COMPLETED = 'ekyc/GET_DISTRICT_COMPLETED'
export const GET_DISTRICT_FAILED = 'ekyc/GET_DISTRICT_FAILED'

export const GET_SUB_BRANCH = 'ekyc/GET_SUB_BRANCH'
export const GET_SUB_BRANCH_COMPLETED = 'ekyc/GET_SUB_BRANCH_COMPLETED'
export const GET_SUB_BRANCH_FAILED = 'ekyc/GET_SUB_BRANCH_FAILED'
export const CHOICE_BRANCH = 'ekyc/CHOICE_BRANCH'
export const CHOICE_COMBO = 'ekyc/CHOICE_COMBO'

export const SEND_REGISTER = 'ekyc/SEND_REGISTER'
export const SEND_REGISTER_COMPLETED = 'ekyc/SEND_REGISTER_COMPLETED'
export const SEND_REGISTER_FAILED = 'ekyc/SEND_REGISTER_FAILED'

export const SAVE_REFERRAL_CODE = 'ekyc/SAVE_REFERRAL_CODE'
export const SAVE_REFERRAL_CODE_COMPLETED = 'ekyc/SAVE_REFERRAL_CODE_COMPLETED'
export const SAVE_REFERRAL_CODE_FAILED = 'ekyc/SAVE_REFERRAL_CODE_FAILED'

export const ACTIVE_EKYC = 'ekyc/ACTIVE_EKYC'
export const ACTIVE_EKYC_COMPLETED = 'ekyc/ACTIVE_EKYC_COMPLETED'
export const ACTIVE_EKYC_FAILED = 'ekyc/ACTIVE_EKYC_FAILED'

export const UPDATE_REQUEST_ID = 'ekyc/UPDATE_REQUEST_ID'

export const RE_ACTIVE = 'login/RE_ACTIVE'
