export const GET_SEC_LIST = 'setting/GET_SEC_LIST'
export const GET_SEC_LIST_COMPLETED = 'setting/GET_SEC_LIST_COMPLETED'
export const GET_SEC_LIST_FAILED = 'setting/GET_SEC_LIST_FAILED'

export const SEND_OTP_VERIFY = 'setting/SEND_OTP_VERIFY'
export const SEND_OTP_VERIFY_COMPLETED = 'setting/SEND_OTP_VERIFY_COMPLETED'
export const SEND_OTP_VERIFY_FAILED = 'setting/SEND_OTP_VERIFY_FAILED'

export const ACTIVE_FP_VERIFY = 'setting/ACTIVE_FP_VERIFY'
export const ACTIVE_FP_VERIFY_COMPLETED = 'setting/ACTIVE_FP_VERIFY_COMPLETED'
export const ACTIVE_FP_VERIFY_FAILED = 'setting/ACTIVE_FP_VERIFY_FAILED'

export const GET_LIMIT_TRANSACTION = 'setting/GET_LIMIT_TRANSACTION'
export const GET_LIMIT_TRANSACTION_COMPLETED = 'setting/GET_LIMIT_TRANSACTION_COMPLETED'
export const GET_LIMIT_TRANSACTION_FAILED = 'setting/GET_LIMIT_TRANSACTION_FAILED'

export const GET_ACCOUNT = 'setting/GET_ACCOUNT'
export const GET_ACCOUNT_COMPLETED = 'setting/GET_ACCOUNT_COMPLETED'
export const GET_ACCOUNT_FAILED = 'setting/GET_ACCOUNT_FAILED'

export const SET_DEFAULT_ACCOUNT = 'setting/SET_DEFAULT_ACCOUNT'
export const SET_DEFAULT_ACCOUNT_COMPLETED = 'setting/SET_DEFAULT_ACCOUNT_COMPLETED'
export const SET_DEFAULT_ACCOUNT_FAILED = 'setting/SET_DEFAULT_ACCOUNT_FAILED'

export const SET_LIMIT_TRANSACTION = 'setting/SET_LIMIT_TRANSACTION'
export const SET_LIMIT_TRANSACTION_COMPLETED = 'setting/SET_LIMIT_TRANSACTION_COMPLETED'
export const SET_LIMIT_TRANSACTION_FAILED = 'setting/SET_LIMIT_TRANSACTION_FAILED'

export const VALID_LIMIT_TRANSACTION = 'setting/VALID_LIMIT_TRANSACTION'
export const VALID_LIMIT_TRANSACTION_COMPLETED = 'setting/VALID_LIMIT_TRANSACTION_COMPLETED'
export const VALID_LIMIT_TRANSACTION_FAILED = 'setting/VALID_LIMIT_TRANSACTION_FAILED'

export const SEND_OTP = 'setting/SEND_OTP'
export const SEND_OTP_COMPLETED = 'setting/SEND_OTP_COMPLETED'
export const SEND_OTP_FAILED = 'setting/SEND_OTP_FAILED'

export const CHANGE_PASS = 'setting/CHANGE_PASS'
export const CHANGE_PASS_COMPLETED = 'setting/CHANGE_PASS_COMPLETED'
export const CHANGE_PASS_FAILED = 'setting/CHANGE_PASS_FAILED'

export const MAKE_TRANSACTION = 'setting/MAKE_TRANSACTION'
export const MAKE_TRANSACTION_COMPLETED = 'setting/MAKE_TRANSACTION_COMPLETED'
export const MAKE_TRANSACTION_FAILED = 'setting/MAKE_TRANSACTION_FAILED'

export const ACTIVE_FP_LOGIN = 'setting/ACTIVE_FP_LOGIN'
export const ACTIVE_FP_LOGIN_COMPLETED = 'setting/ACTIVE_FP_LOGIN_COMPLETED'
export const ACTIVE_FP_LOGIN_FAILED = 'setting/ACTIVE_FP_LOGIN_FAILED'

export const UPDATE_FP_LOGIN = 'setting/UPDATE_FP_LOGIN'
export const UPDATE_FP_LOGIN_COMPLETED = 'setting/UPDATE_FP_LOGIN_COMPLETED'
export const UPDATE_FP_LOGIN_FAILED = 'setting/UPDATE_FP_LOGIN_FAILED'

export const SETUP_PIN = 'setting/SETUP_PIN'
export const SETUP_PIN_COMPLETED = 'setting/SETUP_PIN_COMPLETED'
export const SETUP_PIN_FAILED = 'setting/SETUP_PIN_FAILED'

export const TURN_ON_LOGIN_FP = 'setting/TURN_ON_LOGIN_FP'
export const TURN_OFF_LOGIN_FP = 'setting/TURN_OFF_LOGIN_FP'
export const TURN_ON_LOGIN_PIN = 'setting/TURN_ON_LOGIN_PIN'
export const TURN_OFF_LOGIN_PIN = 'setting/TURN_OFF_LOGIN_PIN'

export const CHANGE_SECURITY_TYPE = 'setting/CHANGE_SECURITY_TYPE'
export const CHANGE_SECURITY_TYPE_COMPLETED = 'setting/CHANGE_SECURITY_TYPE_COMPLETED'
export const CHANGE_SECURITY_TYPE_FAILED = 'setting/CHANGE_SECURITY_TYPE_FAILED'

export const CHANGE_STATUS_SMS = 'setting/CHANGE_STATUS_SMS'
export const CHANGE_STATUS_SMS_COMPLETED = 'setting/CHANGE_STATUS_SMS_COMPLETED'
export const CHANGE_STATUS_SMS_FAILED = 'setting/CHANGE_STATUS_SMS_FAILED'

export const RESET = 'setting/RESET'
