export { default as LoginScreen } from './login/LoginScreen'
export { default as SplashScreen } from './splash/SplashScreen'
export { default as HomeScreen } from './home/HomeScreen'
export { default as LoginOTPScreen } from './login/LoginOTPScreen'
export { default as MainScreen } from './main/MainScreen'
export { default as SettingScreen } from './settings/SettingScreen'
export { default as TransferScreen } from './transfer/TransferScreen'
export { default as AccountScreen } from './account/AccountScreen'
export { default as SignupScreen } from './signup/SignupScreen'
export { default as SignupOTPScreen } from './signup/SignupOTPScreen'
export { default as ForgotScreen } from './forgot/ForgotScreen'
export { default as NotificationScreen } from './notification/NotificationScreen'
export { default as IntroScreen } from './intro/IntroScreen'
export { default as AuthScreen } from './auth/AuthScreen'
export { default as InternalTransfer } from './transfer/internal/InternalTransfer'
export { default as SoftTokenScreen } from './softtoken/SoftTokenScreen'
export { default as InterbankTransfer } from './transfer/interbank/InterbankTransfer'
export { default as BenefitScreen } from './transfer/internal/BenefitScreen'
export { default as TransferConfirm } from './transfer/common/TransferConfirm'
export { default as ScheduleTransfer } from './transfer/common/ScheduleTransfer'
export { default as VerifyTransfer } from './transfer/common/VerifyTransfer'
export { default as SuccessScreen } from './success/SuccessScreen'
export { default as TransferSuccess } from './transfer/common/TransferSuccess'
export { default as ManagerTransfer } from './transfer/schedule/ManagerTransfer'
export { default as ManagerTransferDetail } from './transfer/schedule/ManagerTransferDetail'
export { default as StockTransfer } from './transfer/stock/StockTransfer'
export { default as BenefitInterbank } from './transfer/interbank/BenefitInterbank'
export { default as Failed } from './failed/Failed'
export { default as ManagerBenefit } from './transfer/benefitmanager/ManagerBenefit'
export { default as SettingVerifyOTP } from './settings/verify/SettingVerifyOTP'
export { default as SetupPinScreen } from './settings/pin/SetupPinScreen'
export { default as AuthByPin } from './auth/AuthByPin'
export { default as StockConfirm } from './transfer/stock/StockConfirm'
export { default as StockOtp } from './transfer/stock/StockOtp'
export { default as SaveBenefit } from './transfer/common/SaveBenefit'
export { default as SuccessMess } from './success/SuccessMess'
export { default as ConfirmScreen } from '../components/ConfirmScreen'

// softtoken
export { default as SoftTokenOTP } from './softtoken/SoftTokenOTP'
export { default as SoftTokenTranId } from './softtoken/SoftTokenTranId'
export { default as SoftTokenScanQr } from './softtoken/SoftTokenScanQr'
export { default as SoftTokenChangePin } from './softtoken/SoftTokenChangePin'
export { default as SoftTokenGenOTP } from './softtoken/SoftTokenGenOTP'

// product

export { default as ProductScreen } from './product/ProductScreen'

// bill payment
export { default as BillPaymentScreen } from './product/billPayment/BillPaymentScreen'
export { default as MobilePaymentInputScreen } from './product/billPayment/InputForm/MobilePayment'
export { default as FixedMobilePayment } from './product/billPayment/InputForm/FixedMobilePayment'
export { default as ElectricPayment } from './product/billPayment/InputForm/ElectricPayment'
export { default as TicketForm } from './product/billPayment/InputForm/TicketForm'
export { default as BillPaymentOTPScreen } from './product/billPayment/BillPaymentOTPScreen'
export { default as AutoPaymentOTPScreen } from './product/autoManagerBill/BillPaymentOTPScreen'

// recharge
export { default as RechargeScreen } from './product/recharge/RechargeScreen'
export { default as ListRechargeScreen } from './product/recharge/ListRechargeScreen'
export { default as CardMobileScreen } from './product/recharge/Service/CardMobile'
export { default as BuyCardRechargeScreen } from './product/recharge/Service/BuyCardRecharge'
export { default as BuyCardConfirmScreen } from './product/recharge/Service/confirm/BuyCardConfirm'
export { default as RechargeCardConfirmScreen } from './product/recharge/Service/confirm/RechargeCardConfirm'
export { default as RechargeCardScreen } from './product/recharge/Service/RechargeCard'
export { default as BuyGameCardScreen } from './product/recharge/Service/BuyGameCard'
export { default as BuyGameCardConfirmScreen } from './product/recharge/Service/confirm/BuyGameCardConfirm'
export { default as ServiceSuccessScreen } from './product/recharge/Service/success/ServiceSuccessScreen'
export { default as BuyingCardSuccess } from './product/recharge/Service/success/BuyingCardSuccess'
export { default as RechargeGameSuccess } from './product/recharge/Service/success/RechargeGameSuccess'
export { default as BuyCardRechargeConfirm } from './product/recharge/Service/confirm/BuyCardRechargeConfirm'

export { default as PayFeeScreen } from './product/recharge/Service/PayFee'
export { default as UtilitiesScreen } from './product/utilities/UtilitiesScreen'
export { default as FailedScreen } from './failed/FailedScreen'
export { default as RechargeOTPScreen } from './product/recharge/RechargeOTPScreen'
export { default as HistoryBillPayment } from './product/billPayment/index'
export { default as AutoManagerBillScreen } from './product/autoManagerBill/AutoManagerBillScreen'
export { default as DetailAutoManagerBillScreen } from './product/autoManagerBill/DetailAutoManagerBillScreen'
export { default as ScheduleRecharge } from './product/recharge/common/ScheduleRecharge'

// account
export { default as PaymentAccountScreen } from './account/PaymentAcount'
export { default as SavingAcountScreen } from './account/SavingAcount'
export { default as CreditAcountScreen } from './account/CreditAcount'
export { default as CreditScreen } from './account/CreditAcount/CreditScreen'
export { default as LoanAcountScreen } from './account/LoanAcount'
export { default as CardService } from './account/CreditAcount/CardService'
export { default as CardPINChangeScreen } from './account/CreditAcount/CardPINChangeScreen'
export { default as SuccessCardPayment } from './account/CreditAcount/SuccessCardPayment'
export { default as ExchangeDetailScreen } from './account/PaymentAcount/ExchangeDetail'
export { default as AccountOTPScreen } from './account/CreditAcount/AccountOTPScreen'
export { default as SuccessChangeStatusScreen } from './account/CreditAcount/SuccessChangeStatusScreen'
export { default as ActiveOTPScreen } from './account/CreditAcount/ActiveCardOTP'

// save
export { default as LiveSaveScreen } from './product/save/LiveSaveScreen'
export { default as OpenSaveScreen } from './product/save/OpenSaveScreen'
export { default as SaveScreen } from './product/save/SaveScreen'
export { default as StoreSaveScreen } from './product/save/StoreSaveScreen'
export { default as SubOpenSaveScreen } from './product/save/SubOpenSaveScreen'
export { default as SuccessSaveScreen } from './product/save/SuccessSaveScreen'
export { default as OpenSaveConfirmScreen } from './product/save/OpenSaveConfirmScreen'
export { default as SuccessFinalizationScreen } from './account/SavingAcount/SuccessScreen'
export { default as FailedFinalizationScreen } from './account/SavingAcount/FailedScreen'
export { default as VerifyFinalization } from './account/SavingAcount/VerifyFinalization'
export { default as DepositSaving } from './account/SavingAcount/DepositSaving'
export { default as ScheduleSaving } from './account/SavingAcount/ScheduleSaving'
export { default as SuccessSaveDeposit } from './account/SavingAcount/SuccessDepositSaving'
// saving overdraft
export { default as ODServiceScreen } from './overdraft/saving/ODServiceScreen'
export { default as CreateOD } from './overdraft/saving/CreateOD'

// register
export { default as OpenNewAccount } from './register/OpenNewAccount'
export { default as Register } from './register/Register'
export { default as EkycSucess } from './register/Success'
export { default as Welcome } from './register/Welcome'
export { default as Policy } from './register/Policy'

export { default as ChangeLimit } from './settings/ChangeLimit'
export { default as ChangeAccount } from './settings/ChangeAccount'
export { default as ChangePassScreen } from './settings/changePass/ChangePassScreen'
export { default as ChangePassOTP } from './settings/changePass/ChangePassOTP'

export { default as AddBenefit } from './transfer/benefitmanager/AddBenefit'
export { default as BenefitConfirm } from './transfer/benefitmanager/BenefitConfirm'
export { default as AddBenefitSuccess } from './transfer/benefitmanager/AddBenefitSuccess'

// employee
export { default as EmployeeScreen } from './employee/EmployeeScreen'
export { default as EmployeeOTP } from './employee/EmployeeOTP'
export { default as EmployeeConfirmRegister } from './employee/EmployeeConfirmRegister'
export { default as ScanQrScreen } from './qrcode/ScanQrScreen'
export { default as QrcodeExchange } from './qrcode/QrcodeExchange'
export { default as QrcodeVerify } from './qrcode/QrcodeVerify'
export { default as QrcodeSuccess } from './qrcode/QrcodeSuccess'

export { default as FirstChangePass } from './login/FirstChangePass'
export { default as ForgotOTPScreen } from './forgot/ForgotOTPScreen'
export { default as NotificationDetail } from './notification/NotificationDetail'
export { default as ChangePinScreen } from './settings/pin/ChangePinScreen'
export { default as InfomationScreen } from './settings/info/InfomationScreen'

export { default as ChangeVerifyTransaction } from './settings/verify/ChangeVerifyTransaction'
export { default as RegisterCreditCard } from './loyalty/registerCard/RegisterCreditCard'
export { default as ListWordsScreen } from './loyalty/game/ListWordsScreen'

export { default as FAQScreen } from './faq/FAQScreen'

export { default as OverDraftScreen } from './overdraft/OverDraftScreen'
export { default as OverDraftCondition } from './overdraft/OverDraftCondition'
export { default as OverDraftVerify } from './overdraft/OverDraftVerify'
export { default as OverDraftSuccess } from './overdraft/OverDraftSuccess'

export { default as OpenCardScreen } from './opencard/OpenCardScreen'
export { default as OpenCardInput } from './opencard/OpenCardInput'
export { default as OpenCardBranch } from './opencard/OpenCardBranch'
export { default as OpenCardCondition } from './opencard/OpenCardCondition'
export { default as OpenCardVerify } from './opencard/OpenCardVerify'
export { default as OpenCardSuccess } from './opencard/OpenCardSuccess'
export { default as ExchangeScreen } from './exchange/ExchangeScreen'
export { default as ATMScreen } from './atm/ATMScreen'
