export const CREATION_INFO = 'overdraft/CREATION_INFO'
export const CREATION_INFO_COMPLETED = 'overdraft/CREATION_INFO_COMPLETED'
export const CREATION_INFO_FAILED = 'overdraft/CREATION_INFO_FAILED'

export const LIST_TC_TYPE = 'overdraft/LIST_TC_TYPE'
export const LIST_TC_TYPE_COMPLETED = 'overdraft/LIST_TC_TYPE_COMPLETED'
export const LIST_TC_TYPE_FAILED = 'overdraft/LIST_TC_TYPE_FAILED'

export const GET_PAYMENT_ACCOUNT = 'overdraft/GET_PAYMENT_ACCOUNT'
export const GET_PAYMENT_ACCOUNT_COMPLETED = 'overdraft/GET_PAYMENT_ACCOUNT_COMPLETED'
export const GET_PAYMENT_ACCOUNT_FAILED = 'overdraft/GET_PAYMENT_ACCOUNT_FAILED'

export const PURPOSE_LIST = 'overdraft/PURPOSE_LIST'
export const PURPOSE_LIST_COMPLETED = 'overdraft/PURPOSE_LIST_COMPLETED'
export const PURPOSE_LIST_FAILED = 'overdraft/PURPOSE_LIST_FAILED'

export const SEND_OTP_REGISTER = 'overdraft/SEND_OTP_REGISTER'
export const SEND_OTP_REGISTER_COMPLETED = 'overdraft/SEND_OTP_REGISTER_COMPLETED'
export const SEND_OTP_REGISTER_FAILED = 'overdraft/SEND_OTP_REGISTER_FAILED'


// old
export const GET_ACCOUNT = 'save/GET_ACCOUNT'
export const GET_ACCOUNT_COMPLETED = 'save/GET_ACCOUNT_COMPLETED'
export const GET_ACCOUNT_FAILED = 'save/GET_ACCOUNT_FAILED'

export const GET_LIST_SAVE_ACCOUNT = 'save/GET_LIST_SAVE_ACCOUNT'
export const GET_LIST_SAVE_ACCOUNT_COMPLETED = 'save/GET_LIST_SAVE_ACCOUNT_COMPLETED'
export const GET_LIST_SAVE_ACCOUNT_FAILED = 'save/GET_LIST_SAVE_ACCOUNT_FAILED'

export const GET_SAVING_RATE = 'save/GET_SAVING_RATE'
export const GET_SAVING_RATE_COMPLETED = 'save/GET_SAVING_RATE_COMPLETED'
export const GET_SAVING_RATE_FAILED = 'save/GET_SAVING_RATE_FAILED'

export const GET_PRODUCT_TYPE = 'save/GET_PRODUCT_TYPE'
export const GET_PRODUCT_TYPE_COMPLETED = 'save/GET_PRODUCT_TYPE_COMPLETED'
export const GET_PRODUCT_TYPE_FAILED = 'save/GET_PRODUCT_TYPE_FAILED'

export const GET_CATEGORY = 'save/GET_CATEGORY'
export const GET_CATEGORY_COMPLETED = 'save/GET_CATEGORY_COMPLETED'
export const GET_CATEGORY_FAILED = 'save/GET_CATEGORY_FAILED'

export const CREATE_SAVING = 'save/CREATE_SAVING'
export const CREATE_SAVING_COMPLETED = 'save/CREATE_SAVING_COMPLETED'
export const CREATE_SAVING_FAILED = 'save/CREATE_SAVING_FAILED'

export const CREATE_FINALIZATION = 'save/CREATE_FINALIZATION'
export const SAVE_DATA_FINALIZATION = 'save/SAVE_DATA_FINALIZATION'
export const CREATE_FINALIZATION_COMPLETED = 'save/CREATE_FINALIZATION_COMPLETED'
export const CREATE_FINALIZATION_FAILED = 'save/CREATE_FINALIZATION_FAILED'

export const VERIFY_OTP_FINALIZATION = 'save/VERIFY_OTP_FINALIZATION'
export const VERIFY_OTP_FINALIZATION_COMPLETED = 'save/VERIFY_OTP_FINALIZATION_COMPLETED'
export const VERIFY_OTP_FINALIZATION_FAILED = 'save/VERIFY_OTP_FINALIZATION_FAILED'

export const SAVE_CHANGE_ALIAS_NAME = 'save/SAVE_CHANGE_ALIAS_NAME'
export const SAVE_CHANGE_ALIAS_NAME_COMPLETED = 'save/SAVE_CHANGE_ALIAS_NAME_COMPLETED'
export const SAVE_CHANGE_ALIAS_NAME_FAILED = 'save/SAVE_CHANGE_ALIAS_NAME_FAILED'

export const COMPLETE_SAVING_ONLINE = 'save/COMPLETE_SAVING_ONLINE'
export const COMPLETE_SAVING_ONLINE_COMPLETED = 'save/COMPLETE_SAVING_ONLINE_COMPLETED'
export const COMPLETE_SAVING_ONLINE_FAILED = 'save/COMPLETE_SAVING_ONLINE_FAILED'

export const SAVING_SEND_EMAIL = 'save/SAVING_SEND_EMAIL'
export const SAVING_SEND_EMAIL_COMPLETED = 'save/SAVING_SEND_EMAIL_COMPLETED'
export const SAVING_SEND_EMAIL_FAILED = 'save/SAVING_SEND_EMAIL_FAILED'

export const SAVING_CREATE_CA_FD = 'save/SAVING_CREATE_CA_FD'
export const SAVING_CREATE_CA_FD_COMPLETED = 'save/SAVING_CREATE_CA_FD_COMPLETED'
export const SAVING_CREATE_CA_FD_FAILED = 'save/SAVING_CREATE_CA_FD_FAILED'

export const SAVING_COMPLETE_CA_FD = 'save/SAVING_COMPLETE_CA_FD'
export const SAVING_COMPLETE_CA_FD_COMPLETED = 'save/SAVING_COMPLETE_CA_FD_COMPLETED'
export const SAVING_COMPLETE_CA_FD_FAILED = 'save/SAVING_COMPLETE_CA_FD_FAILED'
export const RESET_CA_FD_FAILED = 'save/RESET_CA_FD_FAILED'

export const CHECK_HOLIDAY = 'save/CHECK_HOLIDAY'
export const CHECK_HOLIDAY_COMPLETED = 'save/CHECK_HOLIDAY_COMPLETED'
export const CHECK_HOLIDAY_FAILED = 'save/CHECK_HOLIDAY_FAILED'
export const RESET_HOLIDAY = 'save/RESET_HOLIDAY'

export const DISPATCH_SCHEDULE = 'save/DISPATCH_SCHEDULE'

export const RESET_STORE = 'save/RESET_STORE'

export const GROUP_TYPE_TERM = 5
export const SECURITY_TYPE = {
  OTP: 'SM',
  SOFT_TOKEN: 'SO',
  FINGER: 'FP',
}

export const RESULT_TYPE = {
  INIT: 0,
  SUCCESS: 1,
  FAIL: -1
}
