export const CREATION_INFO = 'overdraft/CREATION_INFO'
export const CREATION_INFO_COMPLETED = 'overdraft/CREATION_INFO_COMPLETED'
export const CREATION_INFO_FAILED = 'overdraft/CREATION_INFO_FAILED'

export const LIST_TC_TYPE = 'overdraft/LIST_TC_TYPE'
export const LIST_TC_TYPE_COMPLETED = 'overdraft/LIST_TC_TYPE_COMPLETED'
export const LIST_TC_TYPE_FAILED = 'overdraft/LIST_TC_TYPE_FAILED'

export const GET_PAYMENT_ACCOUNT = 'overdraft/GET_PAYMENT_ACCOUNT'
export const GET_PAYMENT_ACCOUNT_COMPLETED = 'overdraft/GET_PAYMENT_ACCOUNT_COMPLETED'
export const GET_PAYMENT_ACCOUNT_FAILED = 'overdraft/GET_PAYMENT_ACCOUNT_FAILED'

export const PURPOSE_LIST = 'overdraft/PURPOSE_LIST'
export const PURPOSE_LIST_COMPLETED = 'overdraft/PURPOSE_LIST_COMPLETED'
export const PURPOSE_LIST_FAILED = 'overdraft/PURPOSE_LIST_FAILED'

export const COMPLETE_REGISTER = 'overdraft/COMPLETE_REGISTER'
export const COMPLETE_REGISTER_COMPLETED = 'overdraft/COMPLETE_REGISTER_COMPLETED'
export const COMPLETE_REGISTER_FAILED = 'overdraft/COMPLETE_REGISTER_FAILED'

export const SEND_OTP_ONLY = 'overdraft/SEND_OTP_ONLY'
export const SEND_OTP_ONLY_COMPLETED = 'overdraft/SEND_OTP_ONLY_COMPLETED'
export const SEND_OTP_ONLY_FAILED = 'overdraft/SEND_OTP_ONLY_FAILED'

export const SEND_OTP_REGISTER = 'overdraft/SEND_OTP_REGISTER'
export const SEND_OTP_REGISTER_COMPLETED = 'overdraft/SEND_OTP_REGISTER_COMPLETED'
export const SEND_OTP_REGISTER_FAILED = 'overdraft/SEND_OTP_REGISTER_FAILED'

export const COMPLETE_TRANSACTION = 'overdraft/COMPLETE_TRANSACTION'


export const GROUP_TYPE_TERM = 5
export const SECURITY_TYPE = {
  OTP: 'SM',
  SOFT_TOKEN: 'SO',
  FINGER: 'FP',
}

export const RESULT_TYPE = {
  INIT: 0,
  SUCCESS: 1,
  FAIL: -1
}
