import {
  LoginScreen,
  LoginOTPScreen,
  MainScreen,
  SignupScreen,
  SignupOTPScreen,
  ForgotScreen,
  TransferScreen,
  NotificationScreen,
  IntroScreen,
  InternalTransfer,
  SoftTokenScreen,
  InterbankTransfer,
  BenefitScreen,
  TransferConfirm,
  ScheduleTransfer,
  ProductScreen,
  BillPaymentScreen,
  MobilePaymentInputScreen,
  FixedMobilePayment,
  ElectricPayment,
  TicketForm,
  SuccessScreen,
  VerifyTransfer,
  RechargeScreen,
  ListRechargeScreen,
  PaymentAccountScreen,
  UtilitiesScreen,
  SavingAcountScreen,
  CreditAcountScreen,
  CreditScreen,
  LoanAcountScreen,
  CardService,
  CardPINChangeScreen,
  LiveSaveScreen,
  SaveScreen,
  StoreSaveScreen,
  OpenSaveScreen,
  ODServiceScreen,
  CreateOD,
  CreateODConfirm,
  SubOpenSaveScreen,
  SuccessSaveScreen,
  OpenSaveConfirmScreen,
  BillPaymentOTPScreen,
  AutoPaymentOTPScreen,
  FailedScreen,
  Register,
  RechargeOTPScreen,
  AuthScreen,
  HistoryBillPayment,
  StockTransfer,
  ManagerTransfer,
  ManagerTransferDetail,
  BenefitInterbank,
  Failed,
  TransferSuccess,
  ManagerBenefit,
  SoftTokenOTP,
  SoftTokenTranId,
  SoftTokenScanQr,
  SoftTokenChangePin,
  SoftTokenGenOTP,
  SettingVerifyOTP,
  ChangeLimit,
  ChangeAccount,
  ChangePassScreen,
  ChangePassOTP,
  SuccessFinalizationScreen,
  FailedFinalizationScreen,
  SuccessCardPayment,
  AddBenefit,
  EmployeeConfirmRegister,
  EmployeeOTP,
  EmployeeScreen,
  VerifyFinalization,
  SetupPinScreen,
  AuthByPin,
  AutoManagerBillScreen,
  DetailAutoManagerBillScreen,
  StockConfirm,
  StockOtp,
  SaveBenefit,
  ExchangeDetailScreen,
  AccountOTPScreen,
  SuccessChangeStatusScreen,
  ScanQrScreen,
  FirstChangePass,
  CardMobileScreen,
  ForgotOTPScreen,
  EkycSucess,
  Policy,
  QrcodeExchange,
  OpenNewAccount,
  ScheduleRecharge,
  BuyCardRechargeScreen,
  RechargeCardScreen,
  BuyCardConfirmScreen,
  QrcodeVerify,
  QrcodeSuccess,
  RechargeCardConfirmScreen,
  BuyGameCardScreen,
  BuyGameCardConfirmScreen,
  PayFeeScreen,
  ServiceSuccessScreen,
  BuyingCardSuccess,
  NotificationDetail,
  ChangePinScreen,
  InfomationScreen,
  RechargeGameSuccess,
  BenefitConfirm,
  AddBenefitSuccess,
  SuccessMess,
  ChangeVerifyTransaction,
  BuyCardRechargeConfirm,
  Welcome,
  RegisterCreditCard,
  ListWordsScreen,
  DepositSaving,
  ScheduleSaving,
  ConfirmScreen,
  SuccessSaveDeposit,
  ActiveOTPScreen,
  FAQScreen,
  OverDraftScreen,
  OverDraftCondition,
  OverDraftVerify,
  OverDraftSuccess,
  OpenCardScreen,
  OpenCardInput,
  OpenCardBranch,
  OpenCardCondition,
  OpenCardVerify,
  OpenCardSuccess,
  ExchangeScreen,
  ATMScreen,
  CreateODVerify,
  CreateODSuccessScreen,
  CloseODScreen
} from '../screens'
import { withAuthentication } from '../enhancers'

const routes = {
  AuthScreen: { name: 'AuthScreen', component: AuthScreen },
  SetupPinScreen: { name: 'SetupPinScreen', component: withAuthentication(SetupPinScreen) },
  AuthByPin: { name: 'AuthByPin', component: AuthByPin },
  LoginScreen: { name: 'LoginScreen', component: LoginScreen },
  FirstChangePass: { name: 'FirstChangePass', component: FirstChangePass },
  MainScreen: { name: 'MainScreen', component: MainScreen },
  LoginOTPScreen: { name: 'LoginOTPScreen', component: LoginOTPScreen },
  SignupScreen: { name: 'SignupScreen', component: SignupScreen },
  SignupOTPScreen: { name: 'SignupOTPScreen', component: SignupOTPScreen },
  ForgotScreen: { name: 'ForgotScreen', component: ForgotScreen },
  TransferScreen: { name: 'TransferScreen', component: withAuthentication(TransferScreen) },
  NotificationScreen: {
    name: 'NotificationScreen',
    component: withAuthentication(NotificationScreen),
  },
  IntroScreen: { name: 'IntroScreen', component: IntroScreen },
  InternalTransfer: {
    name: 'InternalTransfer',
    component: withAuthentication(InternalTransfer),
  },
  SoftTokenScreen: { name: 'SoftTokenScreen', component: SoftTokenScreen },
  InterbankTransfer: {
    name: 'InterbankTransfer',
    component: withAuthentication(InterbankTransfer),
  },
  BenefitScreen: { name: 'BenefitScreen', component: withAuthentication(BenefitScreen) },
  TransferConfirm: { name: 'TransferConfirm', component: withAuthentication(TransferConfirm) },
  ScheduleTransfer: { name: 'ScheduleTransfer', component: withAuthentication(ScheduleTransfer) },
  VerifyTransfer: { name: 'VerifyTransfer', component: withAuthentication(VerifyTransfer) },
  StockTransfer: { name: 'StockTransfer', component: withAuthentication(StockTransfer) },
  ManagerTransfer: { name: 'ManagerTransfer', component: withAuthentication(ManagerTransfer) },
  ManagerTransferDetail: {
    name: 'ManagerTransferDetail',
    component: withAuthentication(ManagerTransferDetail),
  },
  BenefitInterbank: { name: 'BenefitInterbank', component: withAuthentication(BenefitInterbank) },
  AddBenefit: { name: 'AddBenefit', component: withAuthentication(AddBenefit) },
  StockConfirm: {
    name: 'StockConfirm',
    component: withAuthentication(StockConfirm),
  },
  StockOtp: {
    name: 'StockOtp',
    component: withAuthentication(StockOtp),
  },
  SaveBenefit: {
    name: 'SaveBenefit',
    component: withAuthentication(SaveBenefit),
  },
  BenefitConfirm: {
    name: 'BenefitConfirm',
    component: withAuthentication(BenefitConfirm),
  },
  AddBenefitSuccess: {
    name: 'AddBenefitSuccess',
    component: withAuthentication(AddBenefitSuccess),
  },
  // product
  ProductScreen: { name: 'ProductScreen', component: withAuthentication(ProductScreen) },

  // bill payment
  BillPaymentScreen: {
    name: 'BillPaymentScreen',
    component: withAuthentication(BillPaymentScreen),
  },
  MobilePaymentInputScreen: {
    name: 'MobilePaymentInputScreen',
    component: withAuthentication(MobilePaymentInputScreen),
  },
  FixedMobilePayment: {
    name: 'FixedMobilePayment',
    component: withAuthentication(FixedMobilePayment),
  },
  ElectricPayment: { name: 'ElectricPayment', component: withAuthentication(ElectricPayment) },
  TicketForm: { name: 'TicketForm', component: withAuthentication(TicketForm) },

  HistoryBillPayment: {
    name: 'HistoryBillPayment',
    component: withAuthentication(HistoryBillPayment),
  },
  SuccessScreen: { name: 'SuccessScreen', component: SuccessScreen },

  // recharge
  RechargeScreen: { name: 'RechargeScreen', component: withAuthentication(RechargeScreen) },
  ListRechargeScreen: {
    name: 'ListRechargeScreen',
    component: withAuthentication(ListRechargeScreen),
  },
  CardMobileScreen: {
    name: 'CardMobileScreen',
    component: withAuthentication(CardMobileScreen),
  },
  BuyCardRechargeScreen: {
    name: 'BuyCardRechargeScreen',
    component: withAuthentication(BuyCardRechargeScreen),
  },
  BuyCardConfirmScreen: {
    name: 'BuyCardConfirmScreen',
    component: withAuthentication(BuyCardConfirmScreen),
  },
  RechargeCardConfirmScreen: {
    name: 'RechargeCardConfirmScreen',
    component: withAuthentication(RechargeCardConfirmScreen),
  },
  RechargeCardScreen: {
    name: 'RechargeCardScreen',
    component: withAuthentication(RechargeCardScreen),
  },
  BuyGameCardScreen: {
    name: 'BuyGameCardScreen',
    component: withAuthentication(BuyGameCardScreen),
  },
  BuyGameCardConfirmScreen: {
    name: 'BuyGameCardConfirmScreen',
    component: withAuthentication(BuyGameCardConfirmScreen),
  },
  BuyCardRechargeConfirm: {
    name: 'BuyCardRechargeConfirm',
    component: withAuthentication(BuyCardRechargeConfirm),
  },
  PayFeeScreen: {
    name: 'PayFeeScreen',
    component: withAuthentication(PayFeeScreen),
  },
  ServiceSuccessScreen: {
    name: 'ServiceSuccessScreen',
    component: withAuthentication(ServiceSuccessScreen),
  },
  BuyingCardSuccess: {
    name: 'BuyingCardSuccess',
    component: withAuthentication(BuyingCardSuccess),
  },
  RechargeGameSuccess: {
    name: 'RechargeGameSuccess',
    component: withAuthentication(RechargeGameSuccess),
  },

  UtilitiesScreen: { name: 'UtilitiesScreen', component: withAuthentication(UtilitiesScreen) },

  BillPaymentOTPScreen: { name: 'BillPaymentOTPScreen', component: BillPaymentOTPScreen },
  AutoPaymentOTPScreen: { name: 'AutoPaymentOTPScreen', component: AutoPaymentOTPScreen },

  FailedScreen: { name: 'FailedScreen', component: FailedScreen },
  RechargeOTPScreen: { name: 'RechargeOTPScreen', component: RechargeOTPScreen },
  AutoManagerBillScreen: {
    name: 'AutoManagerBillScreen',
    component: withAuthentication(AutoManagerBillScreen),
  },
  DetailAutoManagerBillScreen: {
    name: 'DetailAutoManagerBillScreen',
    component: withAuthentication(DetailAutoManagerBillScreen),
  },
  ScheduleRecharge: { name: 'ScheduleRecharge', component: withAuthentication(ScheduleRecharge) },
  ConfirmScreen: { name: 'ConfirmScreen', component: withAuthentication(ConfirmScreen) },
  // save
  SaveScreen: { name: 'SaveScreen', component: withAuthentication(SaveScreen) },
  LiveSaveScreen: { name: 'LiveSaveScreen', component: LiveSaveScreen },
  StoreSaveScreen: { name: 'StoreSaveScreen', component: StoreSaveScreen },
  OpenSaveScreen: { name: 'OpenSaveScreen', component: withAuthentication(OpenSaveScreen) },
  SubOpenSaveScreen: { name: 'SubOpenSaveScreen', component: SubOpenSaveScreen },
  SuccessSave: { name: 'SuccessSave', component: SuccessSaveScreen },
  OpenSaveConfirmScreen: { name: 'OpenSaveConfirm', component: OpenSaveConfirmScreen },
  VerifyFinalization: { name: 'VerifyFinalization', component: VerifyFinalization },
  DepositSaving: { name: 'DepositSaving', component: DepositSaving },
  ScheduleSaving: { name: 'ScheduleSaving', component: ScheduleSaving },
  SuccessSaveDeposit: { name: 'SuccessSaveDeposit', component: SuccessSaveDeposit },
  
  TransferSuccess: { name: 'TransferSuccess', component: TransferSuccess },
  Failed: { name: 'Failed', component: Failed },
  ManagerBenefit: { name: 'ManagerBenefit', component: withAuthentication(ManagerBenefit) },
  // saving overdraft
  ODServiceScreen: { name: 'ODServiceScreen', component: withAuthentication(ODServiceScreen) },
  CreateOD: { name: 'CreateOD', component: withAuthentication(CreateOD) },
  CreateODConfirm: { name: 'CreateODConfirm', component: withAuthentication(CreateODConfirm) },
  CreateODVerify: { name: 'CreateODVerify', component: withAuthentication(CreateODVerify) },
  CreateODSuccessScreen: { name: 'CreateODSuccessScreen', component: withAuthentication(CreateODSuccessScreen) },
  CloseODScreen: { name: 'CloseODScreen', component: withAuthentication(CloseODScreen) },
  
  
  // softtoken
  SoftTokenOTP: { name: 'SoftTokenOTP', component: SoftTokenOTP },
  SoftTokenScanQr: { name: 'SoftTokenScanQr', component: SoftTokenScanQr },
  SoftTokenTranId: { name: 'SoftTokenTranId', component: SoftTokenTranId },
  SoftTokenChangePin: {
    name: 'SoftTokenChangePin',
    component: SoftTokenChangePin,
  },
  SoftTokenGenOTP: { name: 'SoftTokenGenOTP', component: SoftTokenGenOTP },

  // account
  PaymentAcountScreen: {
    name: 'PaymentAccountScreen',
    component: withAuthentication(PaymentAccountScreen),
  },
  SavingAcountScreen: {
    name: 'SavingAcountScreen',
    component: withAuthentication(SavingAcountScreen),
  },
  CreditAcountScreen: {
    name: 'CreditAcountScreen',
    component: withAuthentication(CreditAcountScreen),
  },
  CreditScreen: {
    name: 'CreditScreen',
    component: withAuthentication(CreditScreen),
  },
  LoanAcountScreen: {
    name: 'LoanAcountScreen',
    component: withAuthentication(LoanAcountScreen),
  },
  SuccessFinalizationScreen: {
    name: 'SuccessFinalizationScreen',
    component: withAuthentication(SuccessFinalizationScreen),
  },
  CardService: { name: 'CardService', component: CardService },
  CardPINChangeScreen: { name: 'CardPINChangeScreen', component: withAuthentication(CardPINChangeScreen) },
  FailedFinalizationScreen: {
    name: 'FailedFinalizationScreen',
    component: withAuthentication(FailedFinalizationScreen),
  },
  SuccessCardPayment: { name: 'SuccessCardPayment', component: SuccessCardPayment },
  ExchangeDetailScreen: {
    name: 'ExchangeDetailScreen',
    component: withAuthentication(ExchangeDetailScreen),
  },
  AccountOTPScreen: {
    name: 'AccountOTPScreen',
    component: withAuthentication(AccountOTPScreen),
  },
  ActiveOTPScreen: {
    name: 'ActiveOTPScreen',
    component: withAuthentication(ActiveOTPScreen),
  },
  SuccessChangeStatusScreen: {
    name: 'SuccessChangeStatusScreen',
    component: withAuthentication(SuccessChangeStatusScreen),
  },

  // regiter
  OpenNewAccount: { name: 'OpenNewAccount', component: OpenNewAccount },
  Register: { name: 'Register', component: Register },
  EkycSucess: { name: 'EkycSucess', component: EkycSucess },
  Welcome: { name: 'Welcome', component: Welcome },
  Policy: { name: 'Policy', component: Policy },

  SettingVerifyOTP: { name: 'SettingVerifyOTP', component: SettingVerifyOTP },
  ChangeLimit: { name: 'ChangeLimit', component: withAuthentication(ChangeLimit) },
  ChangeAccount: { name: 'ChangeAccount', component: withAuthentication(ChangeAccount) },
  ChangePassScreen: { name: 'ChangePassScreen', component: withAuthentication(ChangePassScreen) },
  ChangePassOTP: { name: 'ChangePassOTP', component: withAuthentication(ChangePassOTP) },

  // employee
  EmployeeScreen: { name: 'EmployeeScreen', component: withAuthentication(EmployeeScreen) },
  EmployeeOTP: { name: 'EmployeeOTP', component: withAuthentication(EmployeeOTP) },
  EmployeeConfirmRegister: {
    name: 'EmployeeConfirmRegister',
    component: withAuthentication(EmployeeConfirmRegister),
  },

  ScanQrScreen: { name: 'ScanQrScreen', component: withAuthentication(ScanQrScreen) },
  QrcodeExchange: { name: 'QrcodeExchange', component: withAuthentication(QrcodeExchange) },
  QrcodeVerify: { name: 'QrcodeVerify', component: withAuthentication(QrcodeVerify) },
  QrcodeSuccess: { name: 'QrcodeSuccess', component: withAuthentication(QrcodeSuccess) },

  ForgotOTPScreen: { name: 'ForgotOTPScreen', component: ForgotOTPScreen },
  NotificationDetail: { name: 'NotificationDetail', component: NotificationDetail },
  ChangePinScreen: { name: 'ChangePinScreen', component: withAuthentication(ChangePinScreen) },
  InfomationScreen: { name: 'InfomationScreen', component: withAuthentication(InfomationScreen) },
  SuccessMess: { name: 'SuccessMess', component: SuccessMess },
  ChangeVerifyTransaction: {
    name: 'ChangeVerifyTransaction',
    component: withAuthentication(ChangeVerifyTransaction),
  },
  RegisterCreditCard: {
    name: 'RegisterCreditCard',
    component: withAuthentication(RegisterCreditCard),
  },
  ListWordsScreen: {
    name: 'ListWordsScreen',
    component: withAuthentication(ListWordsScreen),
  },
  FAQScreen: {
    name: 'FAQScreen',
    component: FAQScreen,
  },
  OverDraftScreen: {
    name: 'OverDraftScreen',
    component: withAuthentication(OverDraftScreen),
  },
  OverDraftCondition: {
    name: 'OverDraftCondition',
    component: withAuthentication(OverDraftCondition),
  },
  OverDraftVerify: {
    name: 'OverDraftVerify',
    component: withAuthentication(OverDraftVerify),
  },
  OverDraftSuccess: {
    name: 'OverDraftSuccess',
    component: withAuthentication(OverDraftSuccess),
  },
  OpenCardScreen: {
    name: 'OpenCardScreen',
    component: withAuthentication(OpenCardScreen),
  },
  OpenCardInput: {
    name: 'OpenCardInput',
    component: withAuthentication(OpenCardInput),
  },
  OpenCardBranch: {
    name: 'OpenCardBranch',
    component: withAuthentication(OpenCardBranch),
  },
  OpenCardCondition: {
    name: 'OpenCardCondition',
    component: withAuthentication(OpenCardCondition),
  },
  OpenCardVerify: {
    name: 'OpenCardVerify',
    component: withAuthentication(OpenCardVerify),
  },
  OpenCardSuccess: {
    name: 'OpenCardSuccess',
    component: (OpenCardSuccess),
  },
  ExchangeScreen: {
    name: 'ExchangeScreen',
    component: withAuthentication(ExchangeScreen),
  },
  ATMScreen: {
    name: 'ATMScreen',
    component: withAuthentication(ATMScreen),
  },

}

export { routes }
