/* eslint-disable max-classes-per-file */
import I18n from 'i18n-js'

export class Config {
  SELFIE_PORTRAIT_SANITY_ERROR = {
    image_too_blur: I18n.t('ekyc.sdk_error.image_too_blur'),
    image_too_dark: I18n.t('ekyc.sdk_error.image_too_dark'),
    image_too_bright: I18n.t('ekyc.sdk_error.image_too_bright'),
    face_too_dark: I18n.t('ekyc.sdk_error.face_too_dark'),
    face_too_bright: I18n.t('ekyc.sdk_error.face_too_bright'),
    not_white_background: I18n.t('ekyc.sdk_error.not_white_background'),
    not_qualified: I18n.t('ekyc.sdk_error.not_qualified'),
    image_has_multiple_faces: I18n.t('ekyc.sdk_error.image_has_multiple_faces'),
    image_has_no_faces: I18n.t('ekyc.sdk_error.image_has_no_faces'),
    face_id_is_invalid: I18n.t('ekyc.sdk_error.image_has_no_faces'),
    not_frontal_face: I18n.t('ekyc.sdk_error.not_frontal_face'),
    not_clear_face: I18n.t('ekyc.sdk_error.not_clear_face'),
    not_clear_eyes: I18n.t('ekyc.sdk_error.not_clear_eyes'),
    right: I18n.t('ekyc.sdk_error.right'),
    left: I18n.t('ekyc.sdk_error.left'),
    'open_eye,closed_eye': I18n.t('ekyc.sdk_error.open_eye_closed_eye'),
    'closed_eye,open_eye': I18n.t('ekyc.sdk_error.closed_eye_open_eye'),
    'open_eye,sunglasses': I18n.t('ekyc.sdk_error.open_eye_sunglasses'),
    'sunglasses,open_eye': I18n.t('ekyc.sdk_error.sunglasses_open_eye'),
    'closed_eye,closed_eye': I18n.t('ekyc.sdk_error.closed_eye_closed_eye'),
    'closed_eye,sunglasses': I18n.t('ekyc.sdk_error.closed_eye_sunglasses'),
    'sunglasses,closed_eye': I18n.t('ekyc.sdk_error.sunglasses_closed_eye'),
    'sunglasses,sunglasses': I18n.t('ekyc.sdk_error.sunglasses_sunglasses'),
    invalid_face_movement: I18n.t('ekyc.sdk_error.invalid_face_movement'),
    is_live_false: I18n.t('ekyc.sdk_error.is_live_false'),
    image_has_no_face: I18n.t('ekyc.sdk_error.image_has_no_face'),
    unmatched: I18n.t('ekyc.sdk_error.matched_low'),
    unsure: I18n.t('ekyc.sdk_error.unsure'),
  }

  SANITY_ID_ERROR = {
    image_too_blur: I18n.t('ekyc.sdk_error.image_too_blur'),
    image_too_dark: I18n.t('ekyc.sdk_error.image_too_dark'),
    image_too_bright: I18n.t('ekyc.sdk_error.image_too_bright'),
    image_has_hole: I18n.t('ekyc.sdk_error.image_has_hole'),
    image_has_cut: I18n.t('ekyc.sdk_error.image_has_cut'),
    no_card_detected: I18n.t('ekyc.sdk_error.no_card_detected'),
    nocard_or_multicard_image: I18n.t('ekyc.sdk_error.nocard_or_multicard_image'),
    image_has_hole_and_cut: I18n.t('ekyc.sdk_error.image_has_hole_and_cut'),
    image_nonlive: I18n.t('ekyc.sdk_error.image_nonlive'),
    image1_blurry: I18n.t('ekyc.sdk_error.image1_blurry'),
    image1_dirty: I18n.t('ekyc.sdk_error.image1_dirty'),
    image1_too_dark: I18n.t('ekyc.sdk_error.image1_too_dark'),
    image1_too_bright: I18n.t('ekyc.sdk_error.image1_too_bright'),
    image1_glare: I18n.t('ekyc.sdk_error.image1_glare'),
    image1_glare_safe: I18n.t('ekyc.sdk_error.image1_glare'),
    image1_glare_unsafe: I18n.t('ekyc.sdk_error.image1_glare_unsafe'),
    incomplete: I18n.t('ekyc.sdk_error.incomplete'),
    image2_blurry: I18n.t('ekyc.sdk_error.image2_blurry'),
    image2_dirty: I18n.t('ekyc.sdk_error.image2_dirty'),
    image2_too_dark: I18n.t('ekyc.sdk_error.image2_too_dark'),
    image2_too_bright: I18n.t('ekyc.sdk_error.image2_too_bright'),
    image2_glare: I18n.t('ekyc.sdk_error.image2_glare'),
    image2_glare_safe: I18n.t('ekyc.sdk_error.image2_glare'),
    image2_glare_unsafe: I18n.t('ekyc.sdk_error.image2_glare_unsafe')
  }

  TAMPERING_ERROR = {
    cut: I18n.t('ekyc.sdk_error.cut'),
    hole: I18n.t('ekyc.sdk_error.hole'),
    photocopy: I18n.t('ekyc.sdk_error.photocopy'),
    photocopied: I18n.t('ekyc.sdk_error.photocopied'),
    covered: I18n.t('ekyc.sdk_error.covered'),
    no_card_or_incomplete_card: I18n.t('ekyc.sdk_error.no_card_or_incomplete_card'),
    'non-liveness': I18n.t('ekyc.sdk_error.non_liveness'),
    photo_tampered: I18n.t('ekyc.sdk_error.photo_tampered'),
    info_tampered: I18n.t('ekyc.sdk_error.info_tampered'),
    age_not_match: I18n.t('ekyc.sdk_error.age_not_match'),
    id_not_follow_rule: I18n.t('ekyc.sdk_error.id_not_follow_rule'),
    invalid_expiry_date: I18n.t('ekyc.sdk_error.invalid_expiry_date'),
    card_expired: I18n.t('ekyc.sdk_error.card_expired'),
    incorrect_issue_date: I18n.t('ekyc.sdk_error.incorrect_issue_date'),
    incorrect_native_place: I18n.t('ekyc.sdk_error.incorrect_native_place'),
    abnormal_emblem: I18n.t('ekyc.sdk_error.abnormal_emblem'),
    no_emblem: I18n.t('ekyc.sdk_error.no_emblem'),
    emblem_covered: I18n.t('ekyc.sdk_error.emblem_covered'),
    wrong_format_in_dob: I18n.t('ekyc.sdk_error.wrong_format_in_dob'),
    wrong_font_in_residential_place: I18n.t('ekyc.sdk_error.wrong_font_in_residential_place'),
    wrong_font: I18n.t('ekyc.sdk_error.wrong_font'),
    id_with_printed_fonts: I18n.t('ekyc.sdk_error.id_with_printed_fonts'),
    id_with_typewriter_fonts: I18n.t('ekyc.sdk_error.id_with_typewriter_fonts'),
    wrong_format_in_recognizable_feature_phrase: I18n.t('ekyc.sdk_error.wrong_format_in_recognizable_feature_phrase'),
    tax_name_unmatched: I18n.t('ekyc.sdk_error.tax_name_unmatched'),
    not_in_same_card: I18n.t('ekyc.sdk_error.not_in_same_card'),
  }

  MSB_VERDICT = {
    system_error: I18n.t('ekyc.sdk_error.system_error'),
    permission_missing_error: I18n.t('ekyc.sdk_error.system_error'),
    access_denied_exception: I18n.t('ekyc.sdk_error.access_denied_exception'),
    invalid_parameter_exception: I18n.t('ekyc.sdk_error.invalid_parameter_exception'),
    rate_limit_exception: I18n.t('ekyc.sdk_error.rate_limit_exception'),
    age_not_match: I18n.t('ekyc.sdk_error.age_not_match'),
    id_not_follow_rule: I18n.t('ekyc.sdk_error.id_not_follow_rule'),
    invalid_expiry_date: I18n.t('ekyc.sdk_error.invalid_expiry_date'),
    authentication_missing_error: I18n.t('ekyc.sdk_error.authentication_missing_error'),
    network_error: I18n.t('ekyc.sdk_error.network_error'),
    internal_error: I18n.t('ekyc.sdk_error.internal_error'),
    timeout_error: I18n.t('ekyc.sdk_error.timeout_error'),
    abnormal_emblem: I18n.t('ekyc.sdk_error.abnormal_emblem'),
    sdk_canceled: I18n.t('ekyc.sdk_error.sdk_canceled'),
    internal_server_error: I18n.t('ekyc.sdk_error.internal_server_error'),
    nocard_or_multicard_image: I18n.t('ekyc.sdk_error.nocard_or_multicard_image'),
  }
}

export class ConfigJupiter {
  SELFIE_PORTRAIT_SANITY_ERROR = {
    image_too_blur: 'image_too_blur_Hình chụp khuôn mặt bị mờ',
    image_too_dark: 'image_too_dark_Hình chụp khuôn mặt quá tối',
    image_too_bright: 'image_too_bright_Hình chụp khuôn mặt quá sáng',
    face_too_dark: 'face_too_dark_Khuôn mặt quá tối',
    face_too_bright: 'face_too_bright_Khuôn mặt quá sáng',
    not_white_background: I18n.t('ekyc.sdk_error.not_white_background'),
    not_qualified: 'not_qualified_Khuôn mặt bị che',
    image_has_multiple_faces: 'image_has_multiple_faces_Có nhiều khuôn mặt trong hình chụp',
    image_has_no_faces: 'image_has_no_faces_Không có khuôn mặt trong hình chụp',
    face_id_is_invalid: 'face_id_is_invalid_Không có khuôn mặt trong hình chụp',
    not_frontal_face: 'not_frontal_face_Khuôn mặt không nhìn thẳng',
    not_clear_face: 'not_clear_face_Hình chụp khuôn mặt không rõ',
    not_clear_eyes: 'not_clear_eyes_Hình chụp phần mắt không rõ',
    right: 'right_Khuôn mặt quay sang phải',
    left: 'left_Khuôn mặt quay sang trái',
    'open_eye,closed_eye': 'open_eye,closed_eye_Ảnh chụp khuôn mặt bị nhắm mắt',
    'closed_eye,open_eye': 'closed_eye,open_eye_Ảnh chụp khuôn mặt bị nhắm mắt',
    'open_eye,sunglasses': 'open_eye,sunglasses_Ảnh chụp khuôn mặt đeo kính',
    'sunglasses,open_eye': 'sunglasses,open_eye_Ảnh chụp khuôn mặt đeo kính',
    'closed_eye,closed_eye': 'closed_eye,closed_eye_Ảnh chụp khuôn mặt bị nhắm mắt',
    'closed_eye,sunglasses': 'closed_eye,sunglasses_Ảnh chụp khuôn mặt bị nhắm mắt hoặc đeo kính',
    'sunglasses,closed_eye': 'sunglasses,closed_eye_Ảnh chụp khuôn mặt bị nhắm mắt hoặc đeo kính',
    'sunglasses,sunglasses': 'sunglasses,sunglasses_Ảnh chụp khuôn mặt đeo kính',
    invalid_face_movement: 'invalid_face_movement_Di chuyển khuôn mặt quá nhanh giữa các lần chụp, hoặc Sử dụng các hình ảnh chụp sẵn, hoặc Khách hàng đưa khuôn mặt ra ngoài khung hình chụp',
    is_live_false: 'is_live_false_Người thực hiện các hành động chụp là khác nhau, hoặc Sử dụng các hình ảnh/video quay sẵn để thực hiện',
    unmatched: 'unmatched_Ảnh chụp khuôn mặt không khớp với giấy tờ tùy thân',
    unsure: 'unsure_Ảnh chụp khuôn mặt chưa chắc chắn khớp với giấy tờ tùy thân',
  }

  SANITY_ID_ERROR = {
    image_too_blur: 'image_too_blur_Hình chụp giấy tờ bị mờ',
    image_too_dark: 'image_too_dark_Hình chụp giấy tờ bị thiếu sáng',
    image_too_bright: 'image_too_bright_Hình chụp giấy tờ bị lóa sáng',
    image_has_hole: 'image_has_hole_Hình chụp giấy tờ bị đục lỗ',
    image_has_cut: 'image_has_cut_Hình chụp giấy tờ bị cắt góc',
    no_card_detected: 'no_card_detected_Không có card trong ảnh',
    nocard_or_multicard_image: 'nocard_or_multicard_image_Lỗi OCR: hình chụp không có giấy tờ tùy thân hoặc có nhiều giấy tờ tùy thân',
    image_has_hole_and_cut: 'image_has_hole_and_cut_Hình chụp giấy tờ bị đục lỗ và cắt góc',
    image_nonlive: I18n.t('ekyc.sdk_error.image_nonlive'),
    image1_blurry: 'image1_blurry_Hình chụp mặt trước giấy tờ bị mờ',
    image1_dirty: 'image1_dirty_Hình chụp mặt trước giấy tờ bị bẩn',
    image1_too_dark: 'image1_too_dark_Hình chụp mặt trước giấy tờ bị thiếu sáng',
    image1_too_bright: 'image1_too_bright_Hình chụp mặt trước giấy tờ bị lóa sáng',
    image1_glare: 'image1_glare_Hình chụp mặt trước giấy tờ bị lóa sáng',
    image1_glare_safe: 'image1_glare_safe_Hình chụp mặt trước giấy tờ bị lóa sáng',
    image1_glare_unsafe: 'image1_glare_unsafe_Hình chụp mặt trước giấy tờ bị lóa sáng',
    incomplete: 'incomplete_Hình chụp mặt trước giấy tờ bị thiếu, không đủ hình',
    image2_blurry: 'image2_blurry_Hình chụp mặt sau giấy tờ bị mờ',
    image2_dirty: 'image2_dirty_Hình chụp mặt sau giấy tờ bị bẩn',
    image2_too_dark: 'image2_too_dark_Hình chụp mặt sau giấy tờ bị thiếu sáng',
    image2_too_bright: 'image2_too_bright_Hình chụp mặt sau giấy tờ bị lóa sáng',
    image2_glare: 'image2_glare_Hình chụp mặt sau giấy tờ bị lóa sáng',
    image2_glare_safe: 'image2_glare_safe_Hình chụp mặt sau giấy tờ bị lóa sáng',
    image2_glare_unsafe: 'image2_glare_unsafe_Hình chụp mặt sau giấy tờ bị lóa sáng'
  }

  TAMPERING_ERROR = {
    cut: 'cut_Hình chụp giấy tờ bị mất góc',
    hole: 'hole_Hình chụp giấy tờ bị đục lỗ',
    photocopy: 'photocopy_Giấy tờ photocopy',
    photocopied: 'photocopy_Giấy tờ photocopy',
    covered: 'Một phần của Giấy tờ bị che bởi một vật gì đó',
    no_card_or_incomplete_card: 'Ảnh chụp chỉ chứa một phần giấy tờ hoặc ko có giấy tờ',
    'non-liveness': 'non-liveness_Giấy tờ được chụp lại từ ảnh (ví dụ chụp từ ảnh trên màn hình điện thoại, máy tính ...)',
    photo_tampered: 'photo_tampered_Giấy tờ có dấu hiệu bị thay ảnh',
    info_tampered: 'info_tampered_Giấy tờ có dấu hiệu bị sửa thông tin',
    age_not_match: 'age_not_match_Dự đoán tuổi của Khách hàng trên ảnh thẻ và so sánh với tuổi khách hàng tại thời điểm cấp CMND không trùng khớp, hoặc Dự đoán tuổi của ảnh thẻ trên CMND so với tuổi của CMND không trùng khớp',
    id_not_follow_rule: 'id_not_follow_rule_Số ID giấy tờ tùy thân không đúng theo quy tắc ',
    invalid_expiry_date: 'invalid_expiry_date_Ngày hết hạn giấy tờ không hợp lệ',
    card_expired: 'card_expired_Giấy tờ tùy thân đã hết hạn',
    incorrect_issue_date: 'incorrect_issue_date_CMND được cấp trước năm Khách hàng đủ 13 tuổi',
    incorrect_native_place: 'incorrect_native_place_Nguyên quán không tuân theo quy tắc',
    abnormal_emblem: 'abnormal_emblem_Quốc huy không đúng mẫu',
    no_emblem: 'no_emblem_Quốc huy bị che toàn bộ',
    emblem_covered: 'emblem_covered_Quốc huy bị che một phần',
    wrong_format_in_dob: 'wrong_format_in_dob_Sau "Sinh ngày" có dấu hai chấm (:) của CMND 9 số',
    wrong_font_in_residential_place: 'wrong_font_in_residential_place_Kiểm tra ký tự đặc biệt ở "Nơi ĐKHK thường trú" của CMND 9 số',
    wrong_font: 'wrong_font_Kiểm tra các ký tự đặc biệt trong phần thông tin của CMND 9 số',
    id_with_printed_fonts: 'id_with_printed_fonts_CMND 9 số được cấp trước 22/12/2008 nhưng dùng font chữ in',
    id_with_typewriter_fonts: 'id_with_typewriter_fonts_CMND 9 số được cấp sau 2013 nhưng dùng font chữ đánh máy',
    wrong_format_in_recognizable_feature_phrase: 'wrong_format_in_recognizable_feature_phrase_Kiểm tra dấu hiệu đặc biệt "Đặc điểm nhận dạng" của mặt sau CCCD/CMND 12 số',
    tax_name_unmatched: 'tax_name_unmatched_Thông tin khách hàng trên giấy tờ không khớp với thông tin tra cứu mã số thuế TNCN',
    not_in_same_card: 'not_in_same_card_Kiểm tra mặt trước và mặt sau của CMND/CCCD có dấu hiệu không phải của cùng một CMND/CCCD',
  }

  MSB_VERDICT = {
    system_error: 'system_error_Lỗi hệ thống',
    permission_missing_error: 'system_error_Lỗi hệ thống',
    access_denied_exception: 'access_denied_exception_Truy cập bị từ chối',
    invalid_parameter_exception: 'invalid_parameter_exception_Dữ liệu đầu vào không hợp lệ',
    rate_limit_exception: 'rate_limit_exception_Số lượng yêu cầu vượt quá giới hạn',
    age_not_match: I18n.t('ekyc.sdk_error.age_not_match'),
    id_not_follow_rule: I18n.t('ekyc.sdk_error.id_not_follow_rule'),
    invalid_expiry_date: I18n.t('ekyc.sdk_error.invalid_expiry_date'),
    authentication_missing_error: 'authentication_missing_error_Lỗi xác thực',
    network_error: 'network_error_Lỗi mạng',
    internal_error: 'internal_error_Lỗi nội bộ',
    timeout_error: 'timeout_error_Lỗi kết nối',
    abnormal_emblem: I18n.t('ekyc.sdk_error.abnormal_emblem'),
    sdk_canceled: 'sdk_canceled_SDK bị hủy',
    internal_server_error: 'internal_server_error_Lỗi hệ thống nội bộ',
    nocard_or_multicard_image: 'nocard_or_multicard_image_Lỗi OCR: hình chụp không có giấy tờ tùy thân hoặc có nhiều giấy tờ tùy thân',

  }
}
