import * as React from 'react'
import { useState, Fragment, useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { StyleSheet, View, ImageBackground, Image, SafeAreaView, TouchableOpacity, Dimensions } from 'react-native'
import I18n from 'i18n-js'
import { ScrollView } from 'react-native-gesture-handler';
import HTML from 'react-native-render-html';
import { IGNORED_TAGS } from 'react-native-render-html/src/HTMLUtils';
import { Helpers, Metrics, Colors, ApplicationStyles, Images } from '../../../theme'
import { Text, ConfirmButton, Radio, Topbar, Loader } from '../../../components'
import * as Navigation from '../../../navigation'
import { productOperations } from '../../../state/product'
import { Utils } from '../../../utilities'
import { odSavingOperations } from '../../../state/overdraftSaving'

const styles = StyleSheet.create({
  container: {
    paddingHorizontal: Metrics.small * 1.8,
    backgroundColor: Colors.white,
    marginHorizontal: Metrics.small * 1.8,
    paddingBottom: Metrics.small,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    marginBottom: Metrics.normal,
  },
  image: {
    flex: 1,
    resizeMode: 'contain',
  },
  text: {
    color: Colors.white,
    fontSize: 20,
    alignSelf: 'center',
  },
  titleContainer: {
    alignItems: 'center',
    paddingVertical: Metrics.small,
    borderBottomWidth: 1,
    borderBottomColor: Colors.white,
    marginTop: Metrics.normal,
  },
  title: {
    fontWeight: 'bold',
    textAlign: 'justify',
    fontSize: 12,
    color: Colors.primary2,
  },
  line: {
    marginHorizontal: Metrics.normal,
    marginTop: Metrics.normal,
    height: 1,
    backgroundColor: Colors.line,
  },
  checkBox: {
    marginHorizontal: Metrics.normal,
    paddingVertical: Metrics.normal,
  },
  textCheckBox: {
    fontSize: 12,
    color: '#171D33',
  },
})

const CreateODConfirm = () => {
  const htmlContent = `
  <p style="text-align:justify">Điều 1.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>Giải Th&iacute;ch Từ Ngữ</p>
<p style="text-align:justify">1. MSB: l&agrave; Ng&acirc;n h&agrave;ng Thương mại Cổ phần H&agrave;ng Hải Việt Nam.</p>
<p style="text-align:justify">2. Kh&aacute;ch h&agrave;ng/Người gửi tiền: L&agrave; c&aacute; nh&acirc;n đăng k&yacute; mở v&agrave; được MSB chấp thuận cấp hạn mức thấu chi bảo đảm bằng tiền gửi tiết kiện online tr&ecirc;n k&ecirc;nh ng&acirc;n h&agrave;ng điện tử; đồng thời l&agrave; chủ sở hữu tiền gửi tiết kiệm online mở tại MSB.&nbsp;</p>
<p style="text-align:justify">3. Thấu chi: L&agrave; dịch vụ MSB cung cấp cho kh&aacute;ch h&agrave;ng, theo đ&oacute; MSB đồng &yacute; chấp thuận cho Kh&aacute;ch h&agrave;ng chi vượt số dư C&oacute; tr&ecirc;n t&agrave;i khoản thanh to&aacute;n bằng đồng Việt Nam của Kh&aacute;ch h&agrave;ng tại MSB ph&ugrave; hợp với c&aacute;c quy định của Ph&aacute;p luật v&agrave; MSB về hoạt động thanh to&aacute;n. Kh&aacute;ch h&agrave;ng phải trả l&atilde;i v&agrave; c&aacute;c chi ph&iacute; kh&aacute;c (nếu c&oacute;) tr&ecirc;n số tiền thấu chi v&agrave; ho&agrave;n trả tiền gốc thấu chi trong một thời hạn nhất định.&nbsp;</p>
<p style="text-align:justify">4. Hạn mức thấu chi (HMTC): L&agrave; số tiền tối đa MSB chấp thuận cho Kh&aacute;ch h&agrave;ng được ph&eacute;p thấu chi trong thời hạn quy định theo thỏa thuận giữa MSB v&agrave; Kh&aacute;ch h&agrave;ng được thể hiện trong Bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">5. Ph&iacute; cấp HMTC: Ph&iacute; thu cho việc cấp v&agrave; sử dụng HMTC (nếu c&oacute;)</p>
<p style="text-align:justify">6. Số dư khả dụng của t&agrave;i khoản thấu chi: L&agrave; số dư tr&ecirc;n t&agrave;i khoản tiền gửi thanh to&aacute;n m&agrave; Kh&aacute;ch h&agrave;ng được ph&eacute;p sử dụng. Số dư khả dụng được x&aacute;c định bằng số dư t&agrave;i khoản cộng (+) HMTC trừ (-) số tiền bị phong tỏa tr&ecirc;n t&agrave;i khoản (nếu c&oacute;).</p>
<p style="text-align:justify">7. T&agrave;i khoản thấu chi (TKTC): L&agrave; t&agrave;i khoản MSB cấp cho Kh&aacute;ch h&agrave;ng khi đăng k&yacute; HMTC th&agrave;nh c&ocirc;ng để sử dụng v&agrave;o c&aacute;c mục đ&iacute;ch ph&ugrave; hợp theo quy định ph&aacute;p luật.&nbsp;</p>
<p style="text-align:justify">8. Tiền gửi tiết kiệm online: L&agrave; tiền gửi tiết kiệm c&oacute; kỳ hạn do Kh&aacute;ch h&agrave;ng thực hiện mở v&agrave; đăng k&yacute; tr&ecirc;n k&ecirc;nh Ng&acirc;n h&agrave;ng điện tử của MSB.</p>
<p style="text-align:justify">9. Internet Banking: L&agrave; k&ecirc;nh giao dịch giữa MSB với Kh&aacute;ch h&agrave;ng th&ocirc;ng qua c&aacute;c tr&igrave;nh duyệt web tr&ecirc;n c&aacute;c thiết bị c&oacute; kết nối với Internet.</p>
<p style="text-align:justify">10. OTP (One Time password): L&agrave; mật khẩu sử dụng một lần v&agrave; c&oacute; hiệu lực trong một khoảng thời gian nhất định, thường được sử dụng như một yếu tố thứ 2 để x&aacute;c thực người d&ugrave;ng truy cập do hệ thống khởi tạo mật khẩu của MSB tự động ph&aacute;t sinh ngẫu nhi&ecirc;n v&agrave; gửi đến thiết bị di động của Kh&aacute;ch h&agrave;ng dưới dạng tin nhắn SMS hoặc gi&aacute; trị hiển thị từ thiết bị bảo mật (Token/Soft Token). Thời gian hiệu lực OTP l&agrave; 3 ph&uacute;t nếu dưới dạng tin nhắn SMS v&agrave; 2 ph&uacute;t với gi&aacute; trị hiển thị từ thiết bị bảo mật.</p>
<p style="text-align:justify">11. Token: L&agrave; dụng cụ cung cấp mật khẩu, hoạt động theo phương thức tự tạo c&aacute;c k&yacute; tự một c&aacute;ch ngẫu nhi&ecirc;n v&agrave; thay đổi theo thời gian. Token c&oacute; thời hạn sử dụng v&agrave; thời hạn sử dụng được ghi tr&ecirc;n Token.&nbsp;</p>
<p style="text-align:justify">12. Soft Token: L&agrave; phần mềm cung cấp m&atilde; OTP được c&agrave;i đặt tr&ecirc;n thiết bị di động đ&atilde; đăng k&yacute; với MSB v&agrave; gắn duy nhất với t&agrave;i khoản đăng nhập eBank. M&atilde; OTP được sinh ngẫu nhi&ecirc;n theo thời gian, đồng bộ với hệ thống thanh to&aacute;n trực tuyến của MSB. Khi thực hiện giao dịch thanh to&aacute;n, MSB y&ecirc;u cầu Kh&aacute;ch h&agrave;ng nhập m&atilde; OTP được sinh bởi Soft Token để ho&agrave;n th&agrave;nh giao dịch. Mỗi m&atilde; OTP c&oacute; gi&aacute; trị trong 1 khoảng thời gian nhất định.</p>
<p style="text-align:justify">Điều 2.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>Nguy&ecirc;n Tắc &Aacute;p Dụng</p>
<p style="text-align:justify">1. Bản Điều khoản điều kiện giao dịch chung cho việc cấp hạn mức thấu chi bằng phương tiện điện tử được bảo đảm bằng tiền gửi tiết kiệm online n&agrave;y (&ldquo;Điều khoản điều kiện giao dịch&rdquo;) điều chỉnh mối quan hệ giữa Kh&aacute;ch h&agrave;ng với MSB khi Kh&aacute;ch h&agrave;ng đề nghị mở v&agrave; cấp hạn mức thấu chi bảo đảm bằng tiền gửi tiết kiệm online tr&ecirc;n k&ecirc;nh ng&acirc;n h&agrave;ng điện tử m&agrave; kh&ocirc;ng phải trực tiếp đến c&aacute;c điểm giao dịch của MSB để thực hiện.</p>
<p style="text-align:justify">2. Bản Điều khoản điều kiện giao dịch n&agrave;y c&ugrave;ng với (i) c&aacute;c th&ocirc;ng tin đề nghị về hạn mức, thời hạn, mục đ&iacute;ch v&agrave; phương thức sử dụng HMTC m&agrave; Kh&aacute;ch h&agrave;ng đ&atilde; lựa chọn v&agrave; gửi đến MSB th&ocirc;ng qua hệ thống Ng&acirc;n h&agrave;ng điện tử v&agrave; (ii) bản Điều khoản điều kiện giao dịch chung dịch vụ t&agrave;i khoản thanh to&aacute;n v&agrave; thẻ ghi nợ https://www.msb.com.vn/Bieu-mau-Bieu-phi-va-Lai-suat/1842/3/Bieu-mau v&agrave; (iii) bản Điều khoản điều kiện giao dịch chung dịch vụ ng&acirc;n h&agrave;ng điện tử https://www.msb.com.vn/Bieu-mau-Bieu-phi-va-Lai-suat/1842/3/Bieu-mau, tạo th&agrave;nh một thỏa thuận ho&agrave;n chỉnh, kh&ocirc;ng t&aacute;ch rời, c&oacute; gi&aacute; trị ph&aacute;p l&yacute; như một bản hợp đồng/thỏa thuận cấp hạn mức thấu chi bảo đảm bằng tiền gửi tiết kiệm online tr&ecirc;n k&ecirc;nh ng&acirc;n h&agrave;ng điện tử. Để tr&aacute;nh hiểu nhầm, việc nhắc đến thuật ngữ Điều khoản điều kiện giao dịch được hiểu rằng đ&atilde; bao gồm tất cả c&aacute;c th&ocirc;ng tin v&agrave; văn kiện giao dịch được đề cập ở tr&ecirc;n.</p>
<p style="text-align:justify">3. Kh&aacute;ch h&agrave;ng hiểu v&agrave; cam kết rằng c&aacute;c th&ocirc;ng tin m&agrave; Kh&aacute;ch h&agrave;ng đề nghị cấp HMTC qua Internet Banking; c&aacute;c th&ocirc;ng tin của Kh&aacute;ch h&agrave;ng (bao gồm cả c&aacute;c th&ocirc;ng tin được Kh&aacute;ch h&agrave;ng cập nhật, chỉnh sửa) được tr&iacute;ch xuất từ hệ thống Internet Banking l&agrave; ch&acirc;n thực, khớp đ&uacute;ng v&agrave; l&agrave; một phần kh&ocirc;ng t&aacute;ch rời của bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">4. Kh&aacute;ch h&agrave;ng vui l&ograve;ng đọc kỹ bản Điều khoản điều kiện giao dịch n&agrave;y, Bản Điều khoản điều kiện giao dịch chung dịch vụ t&agrave;i khoản thanh to&aacute;n v&agrave; thẻ ghi nợ https://www.msb.com.vn/Bieu-mau-Bieu-phi-va-Lai-suat/1842/3/Bieu-mau v&agrave; bản Điều khoản điều kiện giao dịch chung dịch vụ ng&acirc;n h&agrave;ng điện tử https://www.msb.com.vn/Bieu-mau-Bieu-phi-va-Lai-suat/1842/3/Bieu-mau trước khi x&aacute;c nhận th&ocirc;ng tin. Việc Kh&aacute;ch h&agrave;ng lựa chọn t&iacute;ch chọn v&agrave; x&aacute;c nhận ĐỒNG &Yacute; với th&ocirc;ng tin đăng tải tr&ecirc;n Internet Banking được hiểu l&agrave; Kh&aacute;ch h&agrave;ng đ&atilde; đọc, đ&atilde; được giải th&iacute;ch đầy đủ, chi tiết v&agrave; đồng &yacute; với nội dung bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">5. Trường hợp Kh&aacute;ch h&agrave;ng kh&ocirc;ng đồng &yacute; với hoặc chưa hiểu biết, nắm r&otilde; c&aacute;c nội dung hoặc kh&ocirc;ng đ&aacute;p ứng được c&aacute;c điều kiện tại bản Điều khoản điều kiện giao dịch n&agrave;y, vui l&ograve;ng kh&ocirc;ng tiếp tục truy cập v&agrave;/hoặc tiếp tục thực hiện c&aacute;c thao t&aacute;c khởi tại HMTC tr&ecirc;n Internet Banking.</p>
<p style="text-align:justify">6. C&aacute;c nội dung kh&ocirc;ng được quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y thực hiện theo quy định tại c&aacute;c bản Điều khoản điều kiện giao dịch chung dịch vụ t&agrave;i khoản thanh to&aacute;n v&agrave; thẻ ghi nợ v&agrave; bản Điều khoản điều kiện giao dịch chung dịch vụ ng&acirc;n h&agrave;ng điện tử v&agrave; thỏa thuận kh&aacute;c giữa MSB với Kh&aacute;ch h&agrave;ng (nếu c&oacute;). Để tr&aacute;nh hiểu nhầm, trường hợp c&oacute; bất kỳ nội dung m&acirc;u thuẫn n&agrave;o giữa bản Điều khoản điều kiện giao dịch n&agrave;y với c&aacute;c bản điều khoản điều kiện n&ecirc;u tr&ecirc;n th&igrave; ưu ti&ecirc;n &aacute;p dụng nội dung của bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">7. Trong qu&aacute; tr&igrave;nh sử dụng dịch vụ, Kh&aacute;ch h&agrave;ng đồng &yacute; rằng MSB c&oacute; quyền đơn phương sửa đổi, bổ sung nội dung bản Điều khoản điều kiện giao dịch n&agrave;y tr&ecirc;n cơ sở ph&ugrave; hợp với quy định Ph&aacute;p luật v&agrave; MSB sẽ ni&ecirc;m yết c&ocirc;ng khai tr&ecirc;n Internet Banking, website www.msb.com.vn v&agrave;/hoặc tại c&aacute;c điểm giao dịch của MSB. Việc Kh&aacute;ch h&agrave;ng tiếp tục sử dụng dịch vụ sau thời điểm hiệu lực của bản Điều khoản điều kiện giao dịch đ&atilde; được sửa đổi, bổ sung được hiểu l&agrave; Kh&aacute;ch h&agrave;ng đ&atilde; chấp thuận c&aacute;c sửa đổi, bổ sung đ&oacute;.</p>
<p style="text-align:justify">Điều 3.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>Điều Kiện Để Được Cấp Hạn Mức Thấu Chi Bằng Phương Tiện Điện Tử</p>
<p style="text-align:justify">1. Kh&aacute;ch h&agrave;ng sử dụng t&ecirc;n truy cập, mật khẩu truy cập v&agrave;o dịch vụ Internet Banking đ&atilde; đăng k&yacute; tại MSB để đăng k&yacute; mở&nbsp;</p>
<p style="text-align:justify">2. Tại thời điểm đề nghị mở hạn mức thấu chi Online, Kh&aacute;ch h&agrave;ng phải đảm bảo đồng thời c&aacute;c điều kiện sau:</p>
<p style="text-align:justify">a. Đ&atilde; mở t&agrave;i khoản thanh to&aacute;n v&agrave; đăng k&yacute; đầy đủ dịch vụ ng&acirc;n h&agrave;ng điện tử tại MSB;&nbsp;</p>
<p style="text-align:justify">b. Kh&aacute;ch h&agrave;ng đ&atilde; c&oacute; tiền gửi tiết kiệm online mở tại MSB &nbsp;</p>
<p style="text-align:justify">c. L&agrave; c&ocirc;ng d&acirc;n c&oacute; quốc tịch duy nhất l&agrave; Việt Nam, từ đủ 18 tuổi trở l&ecirc;n v&agrave; c&oacute; năng lực h&agrave;nh vi d&acirc;n sự đầy đủ theo quy định ph&aacute;p luật Việt Nam;</p>
<p style="text-align:justify">d. Kh&aacute;ch h&agrave;ng kh&ocirc;ng thuộc đối tượng cấm hoặc hạn chế cấp t&iacute;n dụng theo quy định của ph&aacute;p luật v&agrave; quy định nội bộ của MSB từng thời kỳ;</p>
<p style="text-align:justify">e. Kh&aacute;ch h&agrave;ng kh&ocirc;ng nằm trong danh s&aacute;ch đen (Black-list), Watch-list, Block-list của MSB;</p>
<p style="text-align:justify">f. Khoản cấp HMTC của Kh&aacute;ch h&agrave;ng phải được đảm bảo bằng tiền gửi tiết kiệm online mở tại MSB thuộc sở hữu của Kh&aacute;ch h&agrave;ng v&agrave; đang c&ograve;n hiệu lực tại thời điểm cầm cố v&agrave; đề nghị cấp Hạn mức thấu chi Online;</p>
<p style="text-align:justify">g. Khoản cấp HMTC cho Kh&aacute;ch h&agrave;ng nằm trong giới hạn dư nợ của Kh&aacute;ch h&agrave;ng c&aacute; nh&acirc;n, bảo đảm tu&acirc;n thủ quy định về giới hạn tổng dư nợ cho vay c&aacute; nh&acirc;n theo quy định của MSB từng thời kỳ.&nbsp;</p>
<p style="text-align:justify">3. Bằng việc t&iacute;ch chọn đồng &yacute; với bản Điều khoản điều kiện giao dịch n&agrave;y, Kh&aacute;ch h&agrave;ng đồng &yacute; sử dụng tiền gửi tiết kiệm online mở tại MSB (bao gồm to&agrave;n bộ gốc v&agrave; l&atilde;i ph&aacute;t sinh) đ&atilde; được lựa chọn để l&agrave;m t&agrave;i sản cầm cố đảm bảo cho việc cấp HMTC tại MSB.&nbsp;</p>
<p style="text-align:justify">Kể từ thời điểm Kh&aacute;ch h&agrave;ng đăng k&yacute; th&agrave;nh c&ocirc;ng mở TKTC tr&ecirc;n Internet Banking, Kh&aacute;ch h&agrave;ng chấp thuận để MSB được to&agrave;n quyền (i) phong tỏa to&agrave;n bộ gốc v&agrave; l&atilde;i ph&aacute;t sinh của khoản tiền gửi tiết kiệm online v&agrave; (ii) xử l&yacute; t&agrave;i sản cầm cố l&agrave; tiền gửi tiết kiệm online theo quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; c&aacute;c quy định nội bộ của MSB từng thời kỳ. Đồng thời Kh&aacute;ch h&agrave;ng hiểu rằng kh&ocirc;ng được thực hiện c&aacute;c giao dịch li&ecirc;n quan đến tiền gửi tiết kiệm online cho đến khi HMTC được đ&oacute;ng v&agrave; MSB đ&atilde; giải tỏa tiền gửi tiết kiệm online n&agrave;y.</p>
<p style="text-align:justify">Điều 4.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>Hạn Mức, Thời Hạn, Mục Đ&iacute;ch V&agrave; Phương Thức Sử Dụng Hạn Mức Thấu Chi Bằng Phương Tiện Điện Tử:</p>
<p style="text-align:justify">Bằng việc x&aacute;c nhận đồng &yacute; với bản Điều khoản Điều kiện giao dịch n&agrave;y, Kh&aacute;ch h&agrave;ng hiểu rằng MSB đồng &yacute; cấp một HMTC cho Kh&aacute;ch h&agrave;ng với chi tiết hạn mức, thời hạn HMTC, mục đ&iacute;ch v&agrave; phương thức sử dụng HMTC theo c&aacute;c đề nghị m&agrave; Kh&aacute;ch h&agrave;ng đ&atilde; gửi cho MSB th&ocirc;ng qua hệ thống Ng&acirc;n h&agrave;ng điện tử. C&aacute;c th&ocirc;ng tin đề nghị về hạn mức, thời hạn, mục đ&iacute;ch v&agrave; phương thức sử dụng HMTC m&agrave; Kh&aacute;ch h&agrave;ng đ&atilde; lựa chọn v&agrave; gửi đến MSB th&ocirc;ng qua hệ thống Ng&acirc;n h&agrave;ng điện tử l&agrave; một phần đ&iacute;nh k&egrave;m, kh&ocirc;ng t&aacute;ch rời với bản Điều khoản điều kiện giao dịch n&agrave;y, tạo th&agrave;nh một một bản thỏa thuận/ hợp đồng cấp hạn mức thấu chi bảo đảm bằng tiền gửi tiết kiện online ho&agrave;n chỉnh như được quy định tại Điều 2 của bản Điều khoản điều kiện n&agrave;y.</p>
<p style="text-align:justify">Điều 5.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>L&atilde;i Suất Thấu Chi V&agrave; Ph&iacute;, Chi Ph&iacute;</p>
<p style="text-align:justify">1. L&atilde;i suất thấu chi:</p>
<p style="text-align:justify">a. L&atilde;i suất thấu chi trong hạn mở bằng phương tiện điện tử bảo đảm bằng tiền gửi tiết kiệm online được cố định trong suốt thời gian cấp HMTC v&agrave; được MSB th&ocirc;ng b&aacute;o tới Kh&aacute;ch h&agrave;ng qua Internet Banking khi Kh&aacute;ch h&agrave;ng khai b&aacute;o th&ocirc;ng tin v&agrave; đăng k&yacute; HMTC.&nbsp;</p>
<p style="text-align:justify">b. L&atilde;i thấu chi qu&aacute; hạn:</p>
<p style="text-align:justify">- Khoản nợ gốc qu&aacute; hạn phải chịu l&atilde;i suất qu&aacute; hạn bằng 150% l&atilde;i suất thấu chi trong hạn đang &aacute;p dụng tại thời điểm chuyển nợ qu&aacute; hạn tương ứng với thời gian chậm trả.</p>
<p style="text-align:justify">- Đối với khoản l&atilde;i t&iacute;nh tr&ecirc;n nợ gốc m&agrave; đến hạn chưa trả, Kh&aacute;ch h&agrave;ng phải chịu mức l&atilde;i suất chậm trả bằng 10%/năm t&iacute;nh tr&ecirc;n số dư l&atilde;i chậm trả tương ứng với thời gian chậm trả.</p>
<p style="text-align:justify">- L&atilde;i suất qu&aacute; hạn v&agrave; l&atilde;i suất chậm trả l&agrave; cố định, trừ trường hợp c&aacute;c b&ecirc;n c&oacute; thỏa thuận kh&aacute;c.</p>
<p style="text-align:justify">c. Phương thức t&iacute;nh l&atilde;i:&nbsp;</p>
<p style="text-align:justify">Số tiền l&atilde;i =<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>&sum; ( Số dư nợ thực tế &nbsp;x &nbsp;số ng&agrave;y duy tr&igrave; số dư nợ thực tế &nbsp;x &nbsp;L&atilde;i suất t&iacute;nh l&atilde;i)/365</p>
<p style="text-align:justify">Trong đ&oacute;:</p>
<p style="text-align:justify">- Thời hạn t&iacute;nh l&atilde;i được x&aacute;c định từ ng&agrave;y mở HMTC hết ng&agrave;y liền kề trước ng&agrave;y đ&oacute;ng HMTC (t&iacute;nh ng&agrave;y đầu, bỏ ng&agrave;y cuối của thời hạn t&iacute;nh l&atilde;i) v&agrave; thời điểm x&aacute;c định số dư nợ để t&iacute;nh l&atilde;i l&agrave; cuối mỗi ng&agrave;y trong thời hạn t&iacute;nh l&atilde;i;</p>
<p style="text-align:justify">- Số ng&agrave;y duy tr&igrave; dư nợ thực tế: L&agrave; số ng&agrave;y m&agrave; số dư nợ thực tế cuối mỗi ng&agrave;y kh&ocirc;ng thay đổi.&nbsp;</p>
<p style="text-align:justify">- L&atilde;i suất t&iacute;nh l&atilde;i: được t&iacute;nh theo tỷ lệ %/năm tr&ecirc;n cơ sở một năm l&agrave; 365 ng&agrave;y v&agrave; được x&aacute;c định l&agrave; mức l&atilde;i suất thấu chi theo quy định tại điểm a) điều n&agrave;y;</p>
<p style="text-align:justify">2. Ph&iacute;, chi ph&iacute; li&ecirc;n quan đến việc cấp v&agrave; sử dụng HMTC (nếu c&oacute;):&nbsp;</p>
<p style="text-align:justify">a. Kh&aacute;ch h&agrave;ng chịu tr&aacute;ch nhiệm thanh to&aacute;n c&aacute;c khoản ph&iacute; li&ecirc;n quan đến việc MSB cấp v&agrave; cho ph&eacute;p Kh&aacute;ch h&agrave;ng sử dụng HMCT theo quy định của MSB từng thời kỳ v&agrave; sẽ th&ocirc;ng b&aacute;o cho Kh&aacute;ch h&agrave;ng khi ph&aacute;t sinh.</p>
<p style="text-align:justify">b. C&aacute;c loại ph&iacute; li&ecirc;n quan tới dịch vụ t&agrave;i khoản, thanh to&aacute;n thực hiện theo biểu ph&iacute; MSB c&ocirc;ng bố c&ocirc;ng khai tr&ecirc;n website của MSB v&agrave; tại c&aacute;c điểm giao dịch tại thời điểm nộp ph&iacute;. C&aacute;c khoản ph&iacute;, chi ph&iacute; chưa bao gồm thuế gi&aacute; trị gia tăng.</p>
<p style="text-align:justify">c. Trường hợp Kh&aacute;ch h&agrave;ng kh&ocirc;ng thanh to&aacute;n đ&uacute;ng hạn c&aacute;c loại ph&iacute;, chi ph&iacute; n&ecirc;u tr&ecirc;n th&igrave; phải trả l&atilde;i chậm trả bằng 20%/năm t&iacute;nh tr&ecirc;n số tiền chậm trả tương ứng với thời gian chậm trả.</p>
<p style="text-align:justify">d. Kh&aacute;ch h&agrave;ng c&oacute; tr&aacute;ch nhiệm thanh to&aacute;n c&aacute;c khoản ph&iacute;, chi ph&iacute; ph&aacute;t sinh từ việc sử dụng dịch vụ của B&ecirc;n thứu ba li&ecirc;n quan đến khoản vay (nếu c&oacute;) theo y&ecirc;u cầu của MSB.&nbsp;</p>
<p style="text-align:justify">Điều 6.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>Chấm Dứt HMTC&nbsp;</p>
<p style="text-align:justify">HMTC mở bằng phương tiện điện tử c&oacute; thể bị đ&oacute;ng/chấm dứt trong c&aacute;c trường hợp sau:</p>
<p style="text-align:justify">1. Trường hợp chấm dứt HMTC đ&uacute;ng hạn:&nbsp;</p>
<p style="text-align:justify">a) Trước 30 (ba mươi) ng&agrave;y t&iacute;nh đến thời điểm HMTC hết hạn, MSB gửi th&ocirc;ng b&aacute;o qua hệ thống tin nhắn (SMS) cho Kh&aacute;ch h&agrave;ng th&ocirc;ng b&aacute;o về ng&agrave;y HMTC hết hạn.</p>
<p style="text-align:justify">b) Nếu kh&ocirc;ng c&oacute; y&ecirc;u cầu của Kh&aacute;ch h&agrave;ng, hệ thống tự động đ&oacute;ng HMTC của Kh&aacute;ch h&agrave;ng v&agrave;o ng&agrave;y chấm dứt HMTC. Kh&aacute;ch h&agrave;ng sẽ kh&ocirc;ng thực hiện được bất kỳ giao dịch thấu chi n&agrave;o sau ng&agrave;y hết hạn HMTC.</p>
<p style="text-align:justify">c) Kh&aacute;ch h&agrave;ng c&oacute; tr&aacute;ch nhiệm thanh to&aacute;n to&agrave;n bộ gốc, l&atilde;i ph&iacute; dịch vụ (nếu c&oacute;) ph&aacute;t sinh từ v&agrave;o ng&agrave;y cuối c&ugrave;ng của thời hạn cấp HMTC. Trường hợp v&agrave;o ng&agrave;y đến hạn m&agrave; Kh&aacute;ch h&agrave;ng kh&ocirc;ng thanh to&aacute;n đầy đủ v&agrave; đ&uacute;ng hạn c&aacute;c nghĩa vụ t&agrave;i ch&iacute;nh n&agrave;y, Kh&aacute;ch h&agrave;ng đồng &yacute; rằng MSB c&oacute; quyền lựa chọn một hoặc đồng thời c&aacute;c phương thức sau để thanh to&aacute;n to&agrave;n bộ gốc, l&atilde;i, ph&iacute; dịch vụ (nếu c&oacute;): (i) tr&iacute;ch tiền từ T&agrave;i khoản thanh to&aacute;n của Kh&aacute;ch h&agrave;ng mở tại MSB hoặc (ii) tất to&aacute;n tiền gửi tiết kiệm (được đăng k&yacute; l&agrave;m T&agrave;i sản đảm bảo của HMTC) v&agrave; chuyển tiền v&agrave;o t&agrave;i khoản thấu chi để thanh to&aacute;n to&agrave;n bộ nghĩa vụ của Kh&aacute;ch h&agrave;ng.</p>
<p style="text-align:justify">2. Trường hợp chấm dứt HMTC trước hạn:&nbsp;</p>
<p style="text-align:justify">a. Kh&aacute;ch h&agrave;ng chủ động chấm dứt HMTC trước hạn:&nbsp;</p>
<p style="text-align:justify">Kh&aacute;ch h&agrave;ng c&oacute; thể chấm dứt HMTC trước hạn v&agrave; c&oacute; tr&aacute;ch nhiệm thanh to&aacute;n to&agrave;n bộ gốc, l&atilde;i, ph&iacute; v&agrave; chi ph&iacute; ph&aacute;t sinh (nếu c&oacute;) hoặc sử dụng ch&iacute;nh tiền gửi tiết kiệm (được đăng k&yacute; l&agrave; T&agrave;i sản đảm bảo của HMTC) để thanh to&aacute;n to&agrave;n bộ gốc, l&atilde;i, ph&iacute; dịch vụ n&agrave;y trước khi chấm dứt HMTC.</p>
<p style="text-align:justify">b. MSB c&oacute; quyền đơn phương chấm dứt HMTC trước hạn khi xảy ra một trong c&aacute;c trường hợp sau:</p>
<p style="text-align:justify">- Kh&aacute;ch h&agrave;ng sử dụng HMTC sai mục đ&iacute;ch đ&atilde; đăng k&yacute; với MSB theo Bản Điều khoản điều kiện giao dịch n&agrave;y;</p>
<p style="text-align:justify">- Kh&aacute;ch h&agrave;ng kh&ocirc;ng khai b&aacute;o ch&iacute;nh x&aacute;c, đầy đủ th&ocirc;ng tin hoặc kh&ocirc;ng cập nhật c&aacute;c th&ocirc;ng tin li&ecirc;n quan đến việc vay vốn như th&ocirc;ng tin về nh&acirc;n th&acirc;n, t&igrave;nh h&igrave;nh t&agrave;i ch&iacute;nh, t&agrave;i sản v.v&hellip; của Kh&aacute;ch h&agrave;ng theo y&ecirc;u cầu của MSB;</p>
<p style="text-align:justify">- Kh&aacute;ch h&agrave;ng vi phạm c&aacute;c cam kết trong Bản Điều khoản điều kiện n&agrave;y hoặc theo quy định của ph&aacute;p luật hoặc y&ecirc;u cầu của cơ quan nh&agrave; nước c&oacute; thẩm quyền;&nbsp;</p>
<p style="text-align:justify">- Kh&aacute;ch h&agrave;ng bị chết hoặc bị tuy&ecirc;n bố chết; bị tuy&ecirc;n bố hạn chế hoặc mất năng lực h&agrave;nh vi d&acirc;n sự; bị tuy&ecirc;n bố c&oacute; kh&oacute; khăn trong nhận thức, l&agrave;m chủ h&agrave;nh vi, bị khởi tố, bị mất t&iacute;ch; bỏ trốn hoặc vắng mặt kh&ocirc;ng c&oacute; k&yacute; do hợp ph&aacute;p tại nơi cư tr&uacute; từ 03 th&aacute;ng trở l&ecirc;n;</p>
<p style="text-align:justify">- Kh&aacute;ch h&agrave;ng vi phạm bất kỳ nghĩa vụ thanh to&aacute;n n&agrave;o đối với MSB li&ecirc;n quan đến khoản vay, bao gồm nhưng kh&ocirc;ng giới hạn c&aacute;c nghĩa vụ trả gốc, l&atilde;i, ph&iacute;, phạt, bồi thường thiệt hại, chi ph&iacute; kh&aacute;c (nếu c&oacute;);&nbsp;</p>
<p style="text-align:justify">- Kh&aacute;ch h&agrave;ng c&oacute; bất kỳ khoản t&iacute;n dụng n&agrave;o tại MSB hoặc c&aacute;c tổ chức t&iacute;n dụng bị chuyển sang nợ xấu;&nbsp;</p>
<p style="text-align:justify">- Theo y&ecirc;u cầu của MSB tại bất kỳ thời điểm n&agrave;o, khi xảy ra c&aacute;c sự kiện hoặc c&oacute; những diễn biến m&agrave; theo đ&aacute;nh gi&aacute; của MSB sẽ g&acirc;y bất lợi, t&aacute;c động ti&ecirc;u cực đến khả năng trả nợ của Kh&aacute;ch h&agrave;ng cũng như khả năng thanh to&aacute;n của MSB n&oacute;i ri&ecirc;ng v&agrave; hệ thống Ng&acirc;n h&agrave;ng n&oacute;i tr&ecirc;n;&nbsp;</p>
<p style="text-align:justify">- C&aacute;c trường hợp kh&aacute;c theo c&aacute;c thỏa thuận giữa Kh&aacute;ch h&agrave;ng v&agrave; MSB (nếu c&oacute;).</p>
<p style="text-align:justify">c. Khi xảy ra một trong c&aacute;c trường hợp quy định tại Điểm (b) Khoản 2 Điều n&agrave;y, MSB được quyền chủ động đ&oacute;ng HMTC v&agrave; th&ocirc;ng b&aacute;o cho Kh&aacute;ch h&agrave;ng biết l&yacute; do. Kh&aacute;ch h&agrave;ng phải ho&agrave;n trả cho MSB to&agrave;n bộ số dư nợ thấu chi (bao gồm nhưng kh&ocirc;ng giới hạn l&agrave; tiền gốc, tiền l&atilde;i v&agrave; ph&iacute;/phạt) ph&aacute;t sinh theo th&ocirc;ng b&aacute;o của MSB.Trường hợp kh&ocirc;ng thanh to&aacute;n đầy đủ v&agrave; đ&uacute;ng hạn c&aacute;c nghĩa vụ t&agrave;i ch&iacute;nh n&agrave;y, Kh&aacute;ch h&agrave;ng đồng &yacute; rằng MSB c&oacute; quyền lựa chọn một hoặc đồng thời c&aacute;c phương thức được quy định tại Khoản (a), Điều n&agrave;y để thanh to&aacute;n to&agrave;n bộ nghĩa vụ của Kh&aacute;ch h&agrave;ng.</p>
<p style="text-align:justify">d. Khi thực hiện thủ tục trả nợ trước hạn, Kh&aacute;ch h&agrave;ng phải ghi r&otilde; nội dung trả nợ trước hạn trong ủy nhiệm chi, lệnh chuyển tiền hoặc chứng từ kh&aacute;c.</p>
<p style="text-align:justify">e. Nếu MSB nhận được tiền trả nợ trước hạn của Kh&aacute;ch h&agrave;ng trước 16h00 của ng&agrave;y trả nợ trước hạn, ng&agrave;y MSB nhận được tiền trả nợ trước hạn sẽ được t&iacute;nh l&agrave; ng&agrave;y trả nợ trước hạn; Nếu MSB nhận được tiền trả nợ trước hạn của Kh&aacute;ch h&agrave;ng sau 16h00 của ng&agrave;y trả nợ trước hạn, ng&agrave;y trả nợ trước hạn sẽ được t&iacute;nh l&agrave; ng&agrave;y h&ocirc;m sau.&nbsp;</p>
<p style="text-align:justify">f. C&aacute;c khoản nợ bị thu hồi trước hạn theo th&ocirc;ng b&aacute;o của MSB được coi l&agrave; khoản nợ đến hạn v&agrave; MSB c&oacute; quyền &aacute;p dụng c&aacute;c biện ph&aacute;p thu hồi nợ theo thỏa thuận tại bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; quy định của ph&aacute;p luật c&oacute; li&ecirc;n quan.&nbsp;</p>
<p style="text-align:justify">Điều 7. Trả Nợ Gốc, L&atilde;i V&agrave; C&aacute;c Khoản Phải Trả Kh&aacute;c</p>
<p style="text-align:justify">1. Thu nợ g&ocirc;́c:&nbsp;</p>
<p style="text-align:justify">a) Kh&aacute;ch h&agrave;ng phải thanh to&aacute;n (i) to&agrave;n bộ dư nợ gốc thấu chi c&ograve;n lại v&agrave;o ng&agrave;y cuối c&ugrave;ng của thời hạn duy tr&igrave; HMTC hoặc v&agrave;o ng&agrave;y theo th&ocirc;ng b&aacute;o của MSB gửi tới Kh&aacute;ch h&agrave;ng trong trường hợp chấm dứt HMTC trước hạn; (ii) dư nợ gốc thấu chi vượt hạn mức v&agrave;o ng&agrave;y theo th&ocirc;ng b&aacute;o của MSB gửi tới Kh&aacute;ch h&agrave;ng.</p>
<p style="text-align:justify">b) Bằng bản Điều khoản điều kiện giao dịch n&agrave;y, Kh&aacute;ch h&agrave;ng đồng &yacute; rằng:</p>
<p style="text-align:justify">- Khi c&oacute; bất kỳ khoản tiền n&agrave;o ph&aacute;t sinh ghi C&oacute; v&agrave;o TKTC, hệ thống của MSB được quyền tự động thu to&agrave;n bộ/một phần dư nợ gốc đ&atilde; thấu chi của Kh&aacute;ch h&agrave;ng;</p>
<p style="text-align:justify">- Đồng &yacute; v&agrave; ủy quyền kh&ocirc;ng hủy ngang cho MSB tự động tr&iacute;ch tiền từ TKTT để thu nợ gốc thấu chi khi TKTC c&oacute; số dư &lt; 0 (c&ograve;n dư nợ gốc thấu chi). Việc tr&iacute;ch tiền tự động được thực hiện định kỳ 01 lần/ng&agrave;y v&agrave;o thời điểm cuối ng&agrave;y cho đến khi số dư TKTC = 0</p>
<p style="text-align:justify">2. Thu lãi:&nbsp;</p>
<p style="text-align:justify">a) Căn cứ số dư tr&ecirc;n TKTC h&agrave;ng ng&agrave;y, hệ thống sẽ thực hiện t&iacute;nh tổng số l&atilde;i ph&aacute;t sinh trong th&aacute;ng v&agrave; Kh&aacute;ch h&agrave;ng bằng bản Điều khoản điều kiện giao dịch n&agrave;y ủy quyền cho MSB tr&iacute;ch nợ TKTT để thu l&atilde;i v&agrave;o ng&agrave;y cuối c&ugrave;ng của th&aacute;ng. Kh&aacute;ch h&agrave;ng c&oacute; thể lựa chọn phương thức trả l&atilde;i bằng c&aacute;ch chuyển tiền v&agrave;o TKTC hoặc chuyển tiền v&agrave;o TKTT để MSB tự động tr&iacute;ch tiền thu l&atilde;i, v&agrave;o ng&agrave;y thu l&atilde;i.</p>
<p style="text-align:justify">b) MSB được quyền thu hồi c&aacute;c khoản phải trả của Kh&aacute;ch h&agrave;ng đối với MSB ph&aacute;t sinh li&ecirc;n quan đến khoản cấp HMTC được quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y theo thứ tự sau: Nợ gốc, nợ l&atilde;i, c&aacute;c khoản ph&iacute;, c&aacute;c khoản phải trả kh&aacute;c (nếu c&oacute;) v&agrave;/hoặc c&aacute;c thứ tự thu nợ kh&aacute;c do MSB chủ động quyết định ph&ugrave; hợp với quy định ph&aacute;p luật từng thời kỳ.</p>
<p style="text-align:justify">c) Trường hợp Kh&aacute;ch h&agrave;ng c&oacute; nhiều hơn một (01) TKTC, MSB sẽ thu nợ theo thứ tự n&ecirc;u tại Điểm d Khoản n&agrave;y đối với lần lượt từng TKTC, theo nguy&ecirc;n tắc ưu ti&ecirc;n thu nợ trước đối với HMTC mở trước.</p>
<p style="text-align:justify">3. Bằng bản Điều khoản điều kiện giao dịch n&agrave;y, Kh&aacute;ch h&agrave;ng đồng &yacute; rằng trường hợp Kh&aacute;ch h&agrave;ng, v&igrave; bất kỳ l&yacute; do g&igrave;, kh&ocirc;ng trả được bất kỳ khoản nợ n&agrave;o (bao gồm nhưng kh&ocirc;ng giới hạn c&aacute;c khoản: nợ gốc, l&atilde;i, c&aacute;c khoản ph&iacute;, chi ph&iacute;, c&aacute;c khoản phạt) đầy đủ v&agrave; đ&uacute;ng hạn, th&igrave; MSB được to&agrave;n quyền lựa chọn thực hiện một hoặc đồng thời c&aacute;c biện ph&aacute;p dưới đ&acirc;y:</p>
<p style="text-align:justify">a) Khấu trừ c&aacute;c nghĩa vụ thanh to&aacute;n của MSB đối với Kh&aacute;ch h&agrave;ng ph&aacute;t sinh từ c&aacute;c giao dịch kh&aacute;c giữa MSB v&agrave; Kh&aacute;ch h&agrave;ng (nếu c&oacute;);</p>
<p style="text-align:justify">b) Tr&iacute;ch nợ bất kỳ khoản tiền gửi n&agrave;o (tiền gửi tiết kiệm, tiền gửi c&oacute; kỳ hạn, tiền gửi tr&ecirc;n t&agrave;i khoản thanh to&aacute;n) của Kh&aacute;ch h&agrave;ng tại MSB v&agrave;/hoặc tại c&aacute;c tổ chức t&iacute;n dụng kh&aacute;c (nếu c&oacute;) để thu nợ, bao gồm nhưng kh&ocirc;ng giới hạn tiền gốc, l&atilde;i v&agrave; bất kỳ lợi &iacute;ch n&agrave;o ph&aacute;t sinh từ khoản tiền gửi;</p>
<p style="text-align:justify">c) Xử l&yacute; t&agrave;i sản bảo đảm v&agrave; &aacute;p dụng mọi biện ph&aacute;p kh&aacute;c để thu hồi nợ theo quy định của ph&aacute;p luật.</p>
<p style="text-align:justify">4. Kh&aacute;ch h&agrave;ng đồng &yacute; rằng việc &aacute;p dụng một hoặc đồng thời c&aacute;c biện ph&aacute;p n&ecirc;u tại Khoản 3 Điều n&agrave;y tu&acirc;n theo c&aacute;c nguy&ecirc;n tắc sau:</p>
<p style="text-align:justify">a) MSB được to&agrave;n quyền quyết định lựa chọn v&agrave; &aacute;p dụng biện ph&aacute;p ph&ugrave; hợp m&agrave; kh&ocirc;ng phụ thuộc v&agrave;o việc Kh&aacute;ch h&agrave;ng v&agrave;/hoặc bất kỳ người bảo l&atilde;nh/cam kết đồng trả nợ n&agrave;o (nếu c&oacute;) đang trong t&igrave;nh trạng hoặc c&oacute; nguy cơ mất khả năng thanh to&aacute;n dưới bất kỳ h&igrave;nh thức n&agrave;o hay kh&ocirc;ng theo đ&aacute;nh gi&aacute; của MSB, trừ trường hợp ph&aacute;p luật c&oacute; quy định kh&aacute;c.</p>
<p style="text-align:justify">b) C&aacute;c biện ph&aacute;p n&ecirc;u tr&ecirc;n:</p>
<p style="text-align:justify">(i) c&oacute; thể được MSB &aacute;p dụng v&agrave;o bất kỳ thời điểm n&agrave;o, cho d&ugrave; c&aacute;c nghĩa vụ thanh to&aacute;n được khấu trừ hoặc c&aacute;c khoản tiền gửi đến hạn hay chưa đến hạn; v&agrave;</p>
<p style="text-align:justify">(ii) c&oacute; hiệu lực &aacute;p dụng tới khi Kh&aacute;ch h&agrave;ng ho&agrave;n th&agrave;nh tất cả c&aacute;c nghĩa vụ thanh to&aacute;n với MSB theo quy định tại Bản điều khoản điều kiện n&agrave;y. MSB được to&agrave;n quyền thực hiện c&aacute;c biện ph&aacute;p n&ecirc;u tr&ecirc;n theo quy định tại Bản điều khoản điều kiện n&agrave;y m&agrave; kh&ocirc;ng cần bất kỳ chấp thuận n&agrave;o kh&aacute;c của Kh&aacute;ch h&agrave;ng.</p>
<p style="text-align:justify">c) Trường hợp đồng tiền của nghĩa vụ thanh to&aacute;n/ khoản tiền gửi bị khấu trừ kh&aacute;c với đồng tiền trả nợ, MSB được to&agrave;n quyền thực hiện việc quy đổi sang đồng tiền trả nợ theo tỷ gi&aacute; quy đổi do MSB x&aacute;c định tại thời điểm thực hiện biện ph&aacute;p khấu trừ.</p>
<p style="text-align:justify">d) MSB c&oacute; to&agrave;n quyền:</p>
<p style="text-align:justify">(i) t&iacute;nh to&aacute;n v&agrave; điều chỉnh gi&aacute; trị của khoản khấu trừ tại thời điểm thực hiện khấu trừ (nếu c&oacute;) ph&ugrave; hợp theo quy định của ph&aacute;p luật;</p>
<p style="text-align:justify">(ii) lựa chọn bất kỳ nghĩa vụ thanh to&aacute;n/khoản tiền gửi n&agrave;o để thực hiện khấu trừ trong trường hợp Kh&aacute;ch h&agrave;ng c&oacute; nhiều nghĩa vụ thanh to&aacute;n/khoản tiền gửi với MSB theo nhiều văn kiện giao dịch kh&aacute;c nhau;</p>
<p style="text-align:justify">(iii) ph&acirc;n t&aacute;ch, chia nhỏ bất kỳ nghĩa vụ thanh to&aacute;n/khoản tiền gửi n&agrave;o của Kh&aacute;ch h&agrave;ng với MSB để thực hiện t&iacute;nh to&aacute;n v&agrave; khấu trừ theo quy định tại Bản điều khoản điều kiện n&agrave;y v&agrave; ph&ugrave; hợp quy định của ph&aacute;p luật.</p>
<p style="text-align:justify">(iv) Thực hiện bất kỳ h&agrave;nh động n&agrave;o, bao gồm nhưng kh&ocirc;ng giới hạn việc phong tỏa/tạm kh&oacute;a, giải tỏa/bỏ tạm kh&oacute;a t&agrave;i khoản tiền gửi của Kh&aacute;ch h&agrave;ng tại MSB trong phạm vi ph&aacute;p luật cho ph&eacute;p, để thực hiện việc khấu trừ.</p>
<p style="text-align:justify">5. Kh&aacute;ch h&agrave;ng uỷ quyền kh&ocirc;ng huỷ ngang cho MSB được thực hiện bất kỳ thủ tục cần thiết n&agrave;o để y&ecirc;u cầu c&aacute;c tổ chức t&iacute;n dụng kh&aacute;c tất to&aacute;n (nếu c&oacute;) v&agrave; tr&iacute;ch một phần hoặc to&agrave;n bộ tiền gửi từ t&agrave;i khoản của Kh&aacute;ch h&agrave;ng mở tại tổ chức t&iacute;n dụng đ&oacute; để chuyển về t&agrave;i khoản của Kh&aacute;ch h&agrave;ng tại MSB để thu nợ. Số tiền c&ograve;n lại sau khi MSB ho&agrave;n tất việc tr&iacute;ch nợ sẽ được ho&agrave;n trả cho Kh&aacute;ch h&agrave;ng v&agrave;o t&agrave;i khoản thanh to&aacute;n hoặc theo chỉ định của Kh&aacute;ch h&agrave;ng tại thời điểm ho&agrave;n trả ph&ugrave; hợp với quy định ph&aacute;p luật.</p>
<p style="text-align:justify">6. Trường hợp ng&agrave;y đến hạn trả nợ gốc v&agrave;/hoặc l&atilde;i tr&ugrave;ng v&agrave;o ng&agrave;y nghỉ (bao gồm c&aacute;c ng&agrave;y nghỉ h&agrave;ng tuần, ng&agrave;y nghỉ lễ, nghỉ tết v&agrave; c&aacute;c ng&agrave;y nghỉ kh&aacute;c theo quy định của ph&aacute;p luật) th&igrave; ng&agrave;y thanh to&aacute;n gốc v&agrave;/hoặc l&atilde;i chuyển sang ng&agrave;y l&agrave;m việc liền kề tiếp theo, tiền l&atilde;i được t&iacute;nh đến ng&agrave;y thực tế trả nợ. Dư nợ để t&iacute;nh l&atilde;i l&agrave; số dư cuối của ng&agrave;y l&agrave;m việc trước ng&agrave;y đ&oacute;.&nbsp;</p>
<p style="text-align:justify">Điều 8.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>Cơ Cấu Lại Thời Hạn Trả Nợ</p>
<p style="text-align:justify">1. Đến hạn trả nợ (gốc v&agrave; l&atilde;i), nếu Kh&aacute;ch h&agrave;ng chưa c&oacute; khả năng trả nợ, th&igrave; phải gửi Giấy đề nghị cơ cấu lại thời hạn trả nợ cho MSB chậm nhất l&agrave; 10 ng&agrave;y l&agrave;m việc trước mỗi kỳ hạn trả nợ. Giấy đề nghị cơ cấu lại thời hạn trả nợ phải n&ecirc;u r&otilde; l&yacute; do đề nghị điều chỉnh kỳ hạn trả nợ hoặc gia hạn nợ; khả năng, thời hạn v&agrave; nguồn trả nợ, k&egrave;m theo c&aacute;c t&agrave;i liệu chứng minh.</p>
<p style="text-align:justify">2. Trong thời hạn 10 ng&agrave;y l&agrave;m việc trước ng&agrave;y khoản nợ đến hạn, MSB sẽ xem x&eacute;t, đ&aacute;nh gi&aacute; khả năng trả nợ, nguồn trả nợ của Kh&aacute;ch h&agrave;ng v&agrave; c&aacute;c yếu tố kh&aacute;c m&agrave; MSB cho l&agrave; cần thiết v&agrave; th&ocirc;ng b&aacute;o lại cho Kh&aacute;ch h&agrave;ng về:&nbsp;</p>
<p style="text-align:justify">a. Đồng &yacute; cơ cấu lại thời hạn trả nợ cho kh&aacute;ch h&agrave;ng v&agrave; k&yacute; văn bản để x&aacute;c định lịch trả nợ mới;&nbsp;</p>
<p style="text-align:justify">b. Kh&ocirc;ng đồng &yacute; cơ cấu lại thời hạn trả nợ. Trong trường hợp n&agrave;y, Kh&aacute;ch h&agrave;ng phải tiếp tục thực hiện nghĩa vụ trả nợ theo thời hạn đ&atilde; cam kết.</p>
<p style="text-align:justify">Điều 9.<span style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span>Chuyển Nợ Qu&aacute; Hạn</p>
<p style="text-align:justify">1. Một phần hoặc to&agrave;n bộ số dư nợ gốc thấu chi được chuyển sang nợ qu&aacute;n hạn v&agrave;o ng&agrave;y liền sau ng&agrave;y ph&aacute;t sinh một hoặc một số sự kiện sau :&nbsp;</p>
<p style="text-align:justify">a) Kh&aacute;ch h&agrave;ng kh&ocirc;ng thanh to&aacute;n đầy đủ to&agrave;n bộ đối với số dư nợ gốc thấu chi c&ograve;n lại v&agrave;o ng&agrave;y cuối c&ugrave;ng của thời hạn duy tr&igrave; HMTC ;</p>
<p style="text-align:justify">b) Kh&aacute;ch h&agrave;ng kh&ocirc;ng thanh to&aacute;n đầy đủ to&agrave;n bộ đối với số dư nọ gốc thấu chi c&ograve;n lại v&agrave;o ng&agrave;y theo th&ocirc;ng b&aacute;o của MSB gửi tới Kh&aacute;ch h&agrave;ng trong trường hợp chấm dứt HMTC trước hạn theo quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y ;</p>
<p style="text-align:justify">c) Kh&aacute;ch h&agrave;ng kh&ocirc;ng thanh to&aacute;n đầy đủ phần dư nợ gốc thấu chi vượt hạn mức v&agrave;o ng&agrave;y theo th&ocirc;ng b&aacute;o của MSB gửi tới Kh&aacute;ch h&agrave;ng theo quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">2. MSB sẽ th&ocirc;ng b&aacute;o về việc chuyển nợ qu&aacute; hạn theo phương thức do MSB quy định trong từng thời kỳ.</p>
<p style="text-align:justify">Điều 10. Quản L&yacute;, Sử Dụng T&agrave;i Sản Cầm Cố L&agrave; Tiền Gửi Tiết Kiệm Online</p>
<p style="text-align:justify">3. To&agrave;n bộ số dư tiền gửi, số tiền l&atilde;i v&agrave; lợi &iacute;ch vật chất kh&aacute;c ph&aacute;t sinh từ tiền gửi tiết kiệm online (sau đ&acirc;y gọi chung l&agrave; T&agrave;i sản cầm cố) sẽ được MSB phong tỏa v&agrave; chỉ được giải tỏa khi Kh&aacute;ch h&agrave;ng đ&atilde; thực hiện đầy đủ nghĩa vụ với MSB hoặc nghĩa vụ được bảo đảm được thay thế bằng biện ph&aacute;p/t&agrave;i sản bảo đảm kh&aacute;c.</p>
<p style="text-align:justify">4. Kh&aacute;ch h&agrave;ng kh&ocirc;ng được trao đổi, tặng cho, g&oacute;p vốn, chuyển nhượng t&agrave;i sản cầm cố dưới mọi h&igrave;nh thức; kh&ocirc;ng được d&ugrave;ng t&agrave;i sản cầm cố để bảo đảm thực hiện nghĩa vụ kh&aacute;c khi chưa được MSB chấp thuận bằng văn bản.</p>
<p style="text-align:justify">Điều 11. Xử L&yacute; T&agrave;i Sản Cầm Cố</p>
<p style="text-align:justify">1. MSB được to&agrave;n quyền lựa chọn xử l&yacute; một phần hoặc to&agrave;n bộ T&agrave;i sản cầm cố (sau đ&acirc;y gọi chung l&agrave; xử l&yacute; T&agrave;i sản cầm cố) để thu hồi nợ (bao gồm cả thu hồi nợ trước hạn) theo quy định của Ph&aacute;p luật v&agrave; quy định của MSB khi xảy ra một trong những trường hợp dưới đ&acirc;y:</p>
<p style="text-align:justify">a) Nghĩa vụ được bảo đảm theo Hợp đồng n&agrave;y kh&ocirc;ng được thực hiện hoặc thực hiện kh&ocirc;ng đ&uacute;ng, kh&ocirc;ng đầy đủ khi đến hạn trả nợ (kể cả trường hợp phải trả nợ trước hạn theo quy định tại Hợp đồng t&iacute;n dụng);</p>
<p style="text-align:justify">b) C&aacute;c trường hợp Kh&aacute;ch h&agrave;ng vi phạm nghĩa vụ theo Bản điều khoản điều kiện n&agrave;y v&agrave; c&aacute;c cam kết t&iacute;n dụng với MSB m&agrave; kh&ocirc;ng khắc phục hoặc kh&ocirc;ng khắc phục được trong thời hạn do MSB y&ecirc;u cầu;</p>
<p style="text-align:justify">c) Một phần hoặc to&agrave;n bộ T&agrave;i sản cầm cố bị mất, huỷ hoại, hư hỏng hoặc giảm s&uacute;t gi&aacute; trị, nhưng kh&ocirc;ng được bổ sung, thay thế theo đ&uacute;ng y&ecirc;u cầu của MSB;</p>
<p style="text-align:justify">d) Một phần hoặc to&agrave;n bộ T&agrave;i sản cầm cố bị chuyển nhượng, trao đổi, tặng cho, g&oacute;p vốn hoặc bị chuyển quyền sở hữu dưới bất kỳ h&igrave;nh thức n&agrave;o;</p>
<p style="text-align:justify">e) Kh&aacute;ch h&agrave;ng l&agrave; c&aacute; nh&acirc;n bị chết hoặc bị tuy&ecirc;n bố chết; bị tuy&ecirc;n bố hạn chế hoặc mất năng lực h&agrave;nh vi d&acirc;n sự; bị tuy&ecirc;n bố c&oacute; kh&oacute; khăn trong nhận thức, l&agrave;m chủ h&agrave;nh vi; bị khởi tố, bị mất t&iacute;ch; bỏ trốn hoặc vắng mặt kh&ocirc;ng c&oacute; l&yacute; do hợp ph&aacute;p tại nơi cư tr&uacute; từ 3 th&aacute;ng trở l&ecirc;n; ly h&ocirc;n hoặc li&ecirc;n quan đến c&aacute;c sự kiện kh&aacute;c g&acirc;y kh&oacute; khăn cho việc thu hồi nợ;</p>
<p style="text-align:justify">f) Thu hồi nợ cho MSB để bảo đảm quyền ưu ti&ecirc;n của MSB đối với t&agrave;i sản cầm cố trong trường hợp Kh&aacute;ch h&agrave;ng c&oacute; nguy cơ phải thực hiện c&aacute;c nghĩa vụ với b&ecirc;n thứ ba;</p>
<p style="text-align:justify">g) C&aacute;c trường hợp kh&aacute;c do c&aacute;c b&ecirc;n thoả thuận hoặc Ph&aacute;p luật quy định.</p>
<p style="text-align:justify">2. Khi xử l&yacute; T&agrave;i sản cầm cố, MSB được trực tiếp tự động tất to&aacute;n một phần hoặc to&agrave;n bộ T&agrave;i sản cầm cố, lĩnh tất cả c&aacute;c khoản tiền gốc, l&atilde;i ph&aacute;t sinh hoặc chuyển nhượng một phần hoặc to&agrave;n bộ T&agrave;i sản cầm cố m&agrave; kh&ocirc;ng cần th&ecirc;m bất kỳ sự đồng &yacute; n&agrave;o của B&ecirc;n cầm cố.</p>
<p style="text-align:justify">3. Tiền, gi&aacute; trị thu được từ việc xử l&yacute; T&agrave;i sản cầm cố, sau khi trừ chi ph&iacute; bảo quản v&agrave; c&aacute;c chi ph&iacute; kh&aacute;c cho MSB, sẽ được sử dụng để trả nợ cho MSB theo thứ tự ưu ti&ecirc;n thỏa thuận tại Hợp đồng t&iacute;n dụng v&agrave; theo quy định của ph&aacute;p luật:&nbsp;</p>
<p style="text-align:justify">a) Trong trường hợp gi&aacute; trị của T&agrave;i sản cầm cố lớn hơn gi&aacute; trị của nghĩa vụ được bảo đảm th&igrave; MSB thanh to&aacute;n số tiền ch&ecirc;nh lệch đ&oacute; cho B&ecirc;n cầm cố, trừ trường hợp c&oacute; thỏa thuận kh&aacute;c.</p>
<p style="text-align:justify">b) Trong trường hợp gi&aacute; trị của T&agrave;i sản cầm cố thấp hơn gi&aacute; trị của nghĩa vụ được bảo đảm th&igrave; Kh&aacute;ch h&agrave;ng phải tiếp tục thanh to&aacute;n cho phần nghĩa vụ được bảo đảm c&ograve;n lại.&nbsp;</p>
<p style="text-align:justify">Điều 12. Quyền V&agrave; Nghĩa Vụ Của Kh&aacute;ch H&agrave;ng</p>
<p style="text-align:justify">1. Được sử dụng HMTC bằng phương tiện điện tử theo thỏa thuận với MSB tại bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">2. Được thực hiện c&aacute;c giao dịch li&ecirc;n quan đến TKTC bằng phương tiện điện tử theo quy định của ph&aacute;p luật v&agrave; của MSB tại bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">3. Kh&aacute;ch h&agrave;ng c&oacute; tr&aacute;ch nhiệm thực hiện đ&uacute;ng v&agrave; đầy đủ bản Điều khoản điều kiện n&agrave;y v&agrave; c&aacute;c hướng dẫn, y&ecirc;u cầu kh&aacute;c của MSB hiển thị tr&ecirc;n Internet Banking/Mobile Banking, tr&ecirc;n website www.msb.com.vn, tại c&aacute;c điểm giao dịch của MSB (nếu c&oacute;), tr&ecirc;n c&aacute;c k&ecirc;nh giao dịch điện tử kh&aacute;c (nếu c&oacute;) v&agrave;/hoặc tại c&aacute;c th&ocirc;ng b&aacute;o MSB gửi th&agrave;nh c&ocirc;ng tới Kh&aacute;ch h&agrave;ng li&ecirc;n quan tới việc mở, đ&oacute;ng, sử dụng HMTC n&agrave;y.</p>
<p style="text-align:justify">4. Kh&aacute;ch h&agrave;ng phải chịu tr&aacute;ch nhiệm về t&iacute;nh ch&iacute;nh x&aacute;c, ch&acirc;n thực v&agrave; hợp ph&aacute;p của những th&ocirc;ng tin cung cấp cho MSB khi thực hiện mở/đ&oacute;ng v&agrave; c&aacute;c giao dịch kh&aacute;c li&ecirc;n quan đến t&agrave;i khoản thấu chi n&agrave;y.&nbsp;</p>
<p style="text-align:justify">5. Kh&aacute;ch h&agrave;ng c&oacute; tr&aacute;ch nhiệm thực hiện c&aacute;c nghĩa vụ li&ecirc;n quan đến bảo đảm an to&agrave;n th&ocirc;ng tin định danh c&aacute; nh&acirc;n, th&ocirc;ng tin li&ecirc;n quan đến việc đăng k&yacute; T&agrave;i khoản, truy cập v&agrave; sử dụng Internet Banking (bao gồm nhưng kh&ocirc;ng giới hạn t&ecirc;n truy cập, mật khẩu truy cập, OTP v&agrave; c&aacute;c loại mật m&atilde; giao dịch) v&agrave; c&aacute;c thiết bị nhận OTP, c&aacute;c loại mật m&atilde; giao dịch (bao gồm nhưng kh&ocirc;ng giới hạn như Token, Soft Token, thiết bị di động) v&agrave; c&aacute;c nghĩa vụ bảo mật kh&aacute;c theo quy tại bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">6. Kh&aacute;ch h&agrave;ng c&oacute; tr&aacute;ch nhiệm cung cấp, cập nhật đầy đủ v&agrave; đảm bảo t&iacute;nh ch&acirc;n thực, khớp đ&uacute;ng, ch&iacute;nh x&aacute;c v&agrave; kịp thời c&aacute;c th&ocirc;ng tin theo y&ecirc;u cầu của MSB khi Kh&aacute;ch h&agrave;ng mở v&agrave; sử dụng HMTC tr&ecirc;n Internet Banking. Kh&aacute;ch h&agrave;ng ho&agrave;n to&agrave;n chịu tr&aacute;ch nhiệm trước ph&aacute;p luật v&agrave; miễn trừ to&agrave;n bộ tr&aacute;ch nhiệm cho MSB đối với bất kỳ tranh chấp v&agrave;/hoặc h&agrave;nh vi vi phạm ph&aacute;p luật n&agrave;o xuất ơhast từ việc Kh&aacute;ch h&agrave;ng cung cấp, cập nhật th&ocirc;ng tin kh&ocirc;ng trung thực, kh&ocirc;ng khớp đ&uacute;ng v&agrave; kh&ocirc;ng ch&iacute;nh x&aacute;c hay kh&ocirc;ng kịp thời, v&igrave; bất cứ l&yacute; do g&igrave;.</p>
<p style="text-align:justify">7. Bằng bản Điều khoản điều kiện giao dịch n&agrave;y, Kh&aacute;ch h&agrave;ng chấp thuận từ bỏ mọi quyền khiếu nại, khiếu kiện của m&igrave;nh v&agrave; miễn trừ mọi tr&aacute;ch nhiệm v&agrave;/hoặc nghĩa vụ của MSB li&ecirc;n quan (nếu c&oacute;) đến : (i) thiệt hại của Kh&aacute;ch h&agrave;ng ph&aacute;t sinh do lỗi của Kh&aacute;ch h&agrave;ng, d&ugrave; l&agrave; v&ocirc; &yacute; hay cố &yacute;; (ii) bất kỳ h&agrave;nh động cần thiết n&agrave;o của MSB khi Kh&aacute;ch h&agrave;ng kh&ocirc;ng thực hiện đ&uacute;ng v&agrave; đầy đủ bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; c&aacute;c hướng dẫn y&ecirc;u cầu kh&aacute;c của MSB, bao gồm nhưng kh&ocirc;ng giới hạn việc MSB từ chối c&aacute;c y&ecirc;u cầu mở, đ&oacute;ng, sử dụng HMTC của Kh&aacute;ch h&agrave;ng kh&ocirc;ng ph&ugrave; hợp với quy định tại Bản Điều khoản điều kiện giao dịch n&agrave;y, quy định ph&aacute;p luật v&agrave; quy định của MSB từng thời kỳ.</p>
<p style="text-align:justify">8. Kh&aacute;ch h&agrave;ng c&oacute; tr&aacute;ch nhiệm chủ động thường xuy&ecirc;n, li&ecirc;n tục theo d&otilde;i, cập nhật nội dung bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; c&aacute;c th&ocirc;ng tin kh&aacute;c li&ecirc;n quan đến sản phẩm, dịch vụ do MSB cung cấp tr&ecirc;n Internet Banking/Mobile Banking, website www.msb.com.vn v&agrave;/hoặc tại c&aacute;c điểm giao dịch của MSB hoặc bằng c&aacute;c phương thức truyền th&ocirc;ng kh&aacute;c. Kh&aacute;ch h&agrave;ng cũng từ bỏ mọi quyền khiếu nại, khiếu kiện đối với MSB trong trường hợp v&igrave; bất cứ l&yacute; do n&agrave;o m&agrave; Kh&aacute;ch h&agrave;ng kh&ocirc;ng thể cập nhật kịp thời nội dung sửa đổi, bổ sung của bản Điều khoản điều kiện giao dịch n&agrave;y, trừ trường hợp việc chậm trễ do lỗi của MSB.</p>
<p style="text-align:justify">Việc Kh&aacute;ch h&agrave;ng tiếp tục sử dụng HMTC sau thời điểm sửa đổi, bổ sung bản Điều khoản điều kiện giao dịch n&agrave;y đồng nghĩa với việc Kh&aacute;ch h&agrave;ng chấp thuận với c&aacute;c nội dung sửa đổi, bổ sung n&agrave;y.</p>
<p style="text-align:justify">9. C&aacute;c quyền v&agrave; nghĩa vụ kh&aacute;c theo quy định của ph&aacute;p luật v&agrave; quy định tại bản Điều khoản giao dịch n&agrave;y v&agrave; c&aacute;c thỏa thuận kh&aacute;c giữa Kh&aacute;ch h&agrave;ng v&agrave; MSB (nếu c&oacute;).</p>
<p style="text-align:justify">Điều 13. Quyền V&agrave; Nghĩa Vụ Của MSB</p>
<p style="text-align:justify">1. Được quyền từ chối việc mở, đ&oacute;ng HMTC hoặc c&aacute;c giao dịch hợp ph&aacute;p kh&aacute;c li&ecirc;n quan đến HMTC nếu Kh&aacute;ch h&agrave;ng kh&ocirc;ng thực hiện theo đ&uacute;ng c&aacute;c thỏa thuận với MSB tại Bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; quy định của ph&aacute;p luật.</p>
<p style="text-align:justify">2. Được quyền thu ph&iacute; (nếu c&oacute;) theo quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y khi Kh&aacute;ch h&agrave;ng thực hiện c&aacute;c giao dịch li&ecirc;n quan đến thấu chi bằng phương tiện điện tử.</p>
<p style="text-align:justify">3. Bằng bản Điều khoản điều kiện giao dịch n&agrave;y, được Kh&aacute;ch h&agrave;ng chấp thuận miễn trừ mọi tr&aacute;ch nhiệm v&agrave;/hoặc nghĩa vụ của MSB li&ecirc;n quan (nếu c&oacute;) đến thiệt hại của Kh&aacute;ch h&agrave;ng ph&aacute;t sinh do lỗi của Kh&aacute;ch h&agrave;ng, d&ugrave; l&agrave; v&ocirc; &yacute; hay cố &yacute;, phối hợp với hoặc tạo điều kiện cho, d&ugrave; l&agrave; trực tiếp hay gi&aacute;n tiếp, bất kỳ nh&acirc;n vi&ecirc;n n&agrave;o của MSB thực hiện c&aacute;c thủ tục giao dịch t&agrave;i khoản thấu chi kh&ocirc;ng ph&ugrave; hợp với quy định bản Điều khoản điều kiện giao dịch n&agrave;y, quy định ph&aacute;p luật v&agrave; quy định của MSB từng thời kỳ.</p>
<p style="text-align:justify">4. Được quyền sửa đổi, bổ sung nội dung bản Điều khoản điều kiện giao dịch n&agrave;y tr&ecirc;n cơ sở ph&ugrave; hợp với quy định ph&aacute;p luật v&agrave; MSB sẽ ni&ecirc;m yết c&ocirc;ng khai tr&ecirc;n Internet Banking/Mobile Banking, website www.msb.com.vn v&agrave;/hoặc tại c&aacute;c điểm giao dịch của MSB. Trường hợp kh&ocirc;ng đồng &yacute; với nội dung sửa đổi, bổ sung bản Điều khoản điều kiện giao dịch n&agrave;y, Kh&aacute;ch h&agrave;ng c&oacute; quyền chấm dứt việc sử dụng dịch vụ sau khi đ&atilde; ho&agrave;n th&agrave;nh c&aacute;c nghĩa vụ với MSB ph&ugrave; hợp với quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; thỏa thuận kh&aacute;c (nếu c&oacute;) giữa Kh&aacute;ch h&agrave;ng v&agrave; MSB.</p>
<p style="text-align:justify">5. Bảo mật th&ocirc;ng tin li&ecirc;n quan đến Kh&aacute;ch h&agrave;ng v&agrave; c&aacute;c giao dịch của Kh&aacute;ch h&agrave;ng tại MSB trừ trường hợp (i) MSB buộc phải tiết lộ th&ocirc;ng tin theo quy định của ph&aacute;p luật, theo y&ecirc;u cầu của cơ quan nh&agrave; nước c&oacute; thẩm quyền v&agrave;/hoặc (ii) theo quyết định của MSB trong c&aacute;c trường hợp cần thiết cung cấp cho b&ecirc;n thứ ba (như Trung t&acirc;m th&ocirc;ng tin t&iacute;n dụng &ndash; CIC; luật sư; b&ecirc;n bảo đảm; nh&agrave; thầu; b&ecirc;n cung cấp dịch vụ; c&aacute;c c&ocirc;ng ty l&agrave; người c&oacute; li&ecirc;n quan của MSB theo quy định của ph&aacute;p luật v&agrave; c&aacute;c cơ quan, tổ chức, c&aacute; nh&acirc;n kh&aacute;c) để phục vụ hoạt động mua b&aacute;n nợ, xử l&yacute; nợ, kiểm to&aacute;n, tư vấn, th&ocirc;ng tin t&iacute;n dụng v&agrave;/hoặc phục vụ việc MSB b&aacute;n ch&eacute;o sản phẩm nhằm hỗ trợ Kh&aacute;ch h&agrave;ng tiếp cận những sản phẩm dịch vụ t&agrave;i ch&iacute;nh, ng&acirc;n h&agrave;ng ph&ugrave; hợp với quy định ph&aacute;p luật. Bằng việc chấp nhận bản Điều khoản điều kiện n&agrave;y, Kh&aacute;ch h&agrave;ng thừa nhận rằng việc cung cấp th&ocirc;ng tin cho b&ecirc;n thứ ba trong c&aacute;c trường hợp n&ecirc;u tr&ecirc;n được thực hiện ho&agrave;n to&agrave;n v&igrave; lợi &iacute;ch của Kh&aacute;ch h&agrave;ng, đồng thời chấp thuận miễn trừ cho MSB khỏi mọi tr&aacute;ch nhiệm li&ecirc;n qaun đến c&aacute;c tranh chấp ph&aacute;t sinh trực tiếp hoặc gi&aacute;n tiếp từ việc cung cấp th&ocirc;ng tin tr&ecirc;n (nếu c&oacute;) v&agrave;/hoặc (iii) c&aacute;c trường hợp kh&aacute;c khi c&oacute; văn bản chấp thuận của Kh&aacute;ch h&agrave;ng.</p>
<p style="text-align:justify">6. Kh&aacute;ch h&agrave;ng chấp thuận rằng MSB kh&ocirc;ng phải chịu bất kỳ tr&aacute;ch nhiệm n&agrave;o, bao gồm cả tr&aacute;ch nhiệm thanh to&aacute;n c&aacute;c khoản phạt, bồi thường thiệt hại, bồi ho&agrave;n hay bất kỳ chi ph&iacute; li&ecirc;n quan n&agrave;o đối với những thiệt hại, tổn thất của Kh&aacute;ch h&agrave;ng ph&aacute;t sinh do:</p>
<p style="text-align:justify">a) Kh&aacute;ch h&agrave;ng:</p>
<p style="text-align:justify">- V&igrave; bất cứ l&yacute; do g&igrave; kh&ocirc;ng nhận dược hoặc kh&ocirc;ng tiếp cận (c&aacute;c) th&ocirc;ng b&aacute;o đ&atilde; được MSB gửi đi th&agrave;nh c&ocirc;ng, bao gồm nhưng kh&ocirc;ng giới hạn c&aacute;c trường hợp do m&aacute;y t&iacute;nh hoặc Nh&agrave; cung cấp dịch vụ của Kh&aacute;ch h&agrave;ng kh&ocirc;ng đảm bảo khả năng kết nối đường truyền được ổn định, li&ecirc;n tục; Kh&aacute;ch h&agrave;ng kh&ocirc;ng cập nhật kịp thời nội dung thay đổi của bản Điều khoản điều kiện giao dịch n&agrave;y th&ocirc;ng qua c&aacute;c phương thức MSB đ&atilde; lựa chọn th&ocirc;ng b&aacute;o, ni&ecirc;m yết;</p>
<p style="text-align:justify">- Kh&ocirc;ng &aacute;p dụng đầy đủ c&aacute;c biện ph&aacute;p hợp l&yacute; v&agrave; cần thiết nhằm đảm bảo an to&agrave;n th&ocirc;ng tin c&aacute; nh&acirc;n v&agrave; c&aacute;c thiết bị, dữ liệu m&aacute;y t&iacute;nh của Kh&aacute;ch h&agrave;ng theo quy định ph&aacute;p luật v&agrave; bản Điều khoản điều kiện giao dịch n&agrave;y, bao gồm nhưng kh&ocirc;ng giới hạn c&aacute;c trường hợp cố &yacute; hoặc v&ocirc; &yacute; tiết lộ th&ocirc;ng tin li&ecirc;n quan đến c&aacute;c yếu tố định danh, yếu tố bảo mật của Kh&aacute;ch h&agrave;ng v&agrave;/hoặc th&ocirc;ng tin li&ecirc;n quan đến c&aacute;c giao dịch cho bất kỳ người thứ ba n&agrave;o; thay đổi th&ocirc;ng tin số điện thoại, thiết bị nhận OTP, m&atilde; số bảo mật m&agrave; kh&ocirc;ng th&ocirc;ng b&aacute;o trước cho MSB; v&agrave;/hoặc c&aacute;c th&ocirc;ng tin c&aacute; nh&acirc;n, thiết bị điện tử của Qu&yacute; kh&aacute;ch bị người kh&aacute;c giả mạo, đ&aacute;nh cắp hoặc sử dụng tr&aacute;i ph&eacute;p dưới bất kỳ h&igrave;nh thức n&agrave;o, trừ trường hợp do lỗi của MSB;</p>
<p style="text-align:justify">- Bị tiết lộ th&ocirc;ng tin li&ecirc;n quan đến c&aacute;c yếu tố định danh, yếu tố bảo mật v&agrave;/hoặc th&ocirc;ng tin li&ecirc;n quan đến c&aacute;c giao dịch nhưng kh&ocirc;ng xuất ph&aacute;t do lỗi của Kh&aacute;ch h&agrave;ng hay MSB bao gồm nhưng kh&ocirc;ng giới hạn c&aacute;c trường hợp do lỗi của nh&agrave; cung cấp dịch vụ viễn th&ocirc;ng của Kh&aacute;ch h&agrave;ng hay bất kỳ b&ecirc;n thứ ba n&agrave;o kh&aacute;c;</p>
<p style="text-align:justify">- Kh&ocirc;ng thực hiện đ&uacute;ng v&agrave; đầy đủ theo quy định của ph&aacute;p luật, quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y, v&agrave; c&aacute;c thỏa thuận kh&aacute;c giữa Kh&aacute;ch h&agrave;ng v&agrave; MSB (nếu c&oacute;).</p>
<p style="text-align:justify">b) MSB</p>
<p style="text-align:justify">- Từ chối cấp HMTC cho Kh&aacute;ch h&agrave;ng hoặc từ chối cho ph&eacute;p Kh&aacute;ch h&agrave;ng thực hiện/tiếp tục thực hiện bất kỳ h&agrave;nh động n&agrave;o li&ecirc;n quan đến HMTC được cấp tr&ecirc;n Internet Banking, cho d&ugrave; h&agrave;nh động đ&oacute; đ&atilde; v&agrave; đang được diễn ra; m&agrave; theo đ&aacute;nh gi&aacute; của MSB, những h&agrave;nh động đ&oacute; c&oacute; dấu hiệu khả nghi, bất thường, c&oacute; dấu hiệu gian lận giả mạo hoặc kh&ocirc;ng hợp ph&aacute;p, hợp lệ theo quy định của MSB v&agrave;/hoặc quy định ph&aacute;p luật v&agrave;/hoặc quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y, bao gồm nhưng kh&ocirc;ng giới hạn c&aacute;c trường hợp Kh&aacute;ch h&agrave;ng trở th&agrave;nh c&aacute;c đối tượng bị hạn chế hoặc bị cấm cấp t&iacute;n dụng theo quy định ph&aacute;p luật;</p>
<p style="text-align:justify">- Tiến h&agrave;nh c&aacute;c hoạt động n&acirc;ng cấp, bảo tr&igrave;, bảo dưỡng hệ thống, cơ sở hạ tầng kỹ thuật định kỳ hoặc đột xuất m&agrave; c&oacute; thể dẫn tới việc cung cấp dịch vụ bị gi&aacute;n đoạn, chậm trễ, kh&ocirc;ng li&ecirc;n tục nhưng đ&atilde; th&ocirc;ng b&aacute;o trước th&ocirc;ng qua c&aacute;c phương thức ph&ugrave; hợp với quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y;</p>
<p style="text-align:justify">- Kh&ocirc;ng thể cung cấp dịch vụ kịp thời, li&ecirc;n tục do (i) MSB tiến h&agrave;nh c&aacute;c hoạt động n&acirc;ng cấp, bảo tr&igrave;, bảo dưỡng hệ thống, cơ sở hạ tầng kỹ thuật định kỳ hoặc đột xuất nhưng đ&atilde; th&ocirc;ng b&aacute;o trước th&ocirc;ng qua c&aacute;c phương thức ph&ugrave; hợp với quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y; hoặc (ii) những nguy&ecirc;n nh&acirc;n ngo&agrave;i khả năng kiểm so&aacute;t hợp l&yacute; của MSB, bao gồm nhưng kh&ocirc;ng giới hạn c&aacute;c trường hợp hệ thống, hạ tầng kỹ thuật của MSB gặp sự cố xuất ph&aacute;t từ lỗi của Nh&agrave; cung cấp dịch vụ của MSB hoặc hệ thống, hạ tầng kỹ thuật của MSB bị x&acirc;m phạm, l&agrave;m hại bởi c&aacute;c loại virus, phần mềm gi&aacute;n điệp, phần mềm quảng c&aacute;o hay bất kỳ h&agrave;nh động can thiệp, tấn c&ocirc;ng mạng nhằm mục đ&iacute;ch ph&aacute; hoại, g&acirc;y hại n&agrave;o;</p>
<p style="text-align:justify">- Thực hiện đơn phương chấm dứt HMTC của Kh&aacute;ch h&agrave;ng theo quy định tại Điểm (b) Khoản 2 Điều 6 bản Điều khoản điều kiện giao dịch n&agrave;y.</p>
<p style="text-align:justify">- Xảy ra những sự kiện bất khả kh&aacute;ng nằm ngo&agrave;i khả năng kiểm so&aacute;t của MSB v&agrave; trực tiếp g&acirc;y ra tổn thất, thiệt hại cho Kh&aacute;ch h&agrave;ng v&agrave; cản trở khả năng của MSB trong qu&aacute; tr&igrave;nh thực hiện c&aacute;c nghĩa vụ đối với Kh&aacute;ch h&agrave;ng, bao gồm nhưng kh&ocirc;ng giới hạn chiến tranh hoặc nội chiến, thi&ecirc;n tai, dịch bệnh, đ&igrave;nh c&ocirc;ng, b&atilde;i c&ocirc;ng, thay đổi ph&aacute;p luật hoặc c&aacute;c sự kiện bất khả kh&aacute;ng kh&aacute;c theo quy định của ph&aacute;p luật hoặc theo tuy&ecirc;n bố, y&ecirc;u cầu của cơ quan nh&agrave; nước c&oacute; thẩm quyền, bất kể (những) sự kiện n&agrave;y ph&aacute;t sinh trong hoặc ngo&agrave;i Việt Nam.</p>
<p style="text-align:justify">- C&aacute;c trường hợp MSB được miễn tr&aacute;ch kh&aacute;c theo quy định ph&aacute;p luật, quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; c&aacute;c thỏa thuận kh&aacute;c giữa Kh&aacute;ch h&agrave;ng v&agrave; MSB (nếu c&oacute;).</p>
<p style="text-align:justify">7. MSB được quyền ph&aacute;t triển c&aacute;c sản phẩm, dịch vụ, t&iacute;nh năng mới tr&ecirc;n Internet Banking ph&ugrave; hợp với quy định của ph&aacute;p luật m&agrave; kh&ocirc;ng phải được Kh&aacute;ch h&agrave;ng chấp thuận dưới bất kỳ h&igrave;nh thức n&agrave;o.</p>
<p style="text-align:justify">8. C&aacute;c quyền v&agrave; nghĩa vụ kh&aacute;c theo quy định của ph&aacute;p luật v&agrave; quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y v&agrave; c&aacute;c thỏa thuận kh&aacute;c giữa Kh&aacute;ch h&agrave;ng v&agrave; MSB (nếu c&oacute;).</p>
<p style="text-align:justify">Điều 14. Th&ocirc;ng B&aacute;o V&agrave; Xử L&yacute; Tra So&aacute;t Khiếu Nại</p>
<p style="text-align:justify">1. MSB c&oacute; quyền gửi th&ocirc;ng tin theo quy định tại bản Điều khoản điều kiện giao dịch n&agrave;y cho Kh&aacute;ch h&agrave;ng th&ocirc;ng qua một hoặc nhiều phương thức do MSB to&agrave;n quyền quyết định bao gồm ni&ecirc;m yết tr&ecirc;n Internet Banking; tin nhắn SMS, địa chỉ email theo th&ocirc;ng tin Kh&aacute;ch đ&atilde; đăng k&yacute; khi đề nghị mở HMTC tr&ecirc;n Internet Banking.</p>
<p style="text-align:justify">2. Th&ocirc;ng b&aacute;o được coi l&agrave; đ&atilde; gửi v&agrave; Kh&aacute;ch h&agrave;ng đ&atilde; nhận th&agrave;nh c&ocirc;ng khi th&ocirc;ng b&aacute;o đ&oacute; (a) được gửi trực tiếp tới tay Kh&aacute;ch h&agrave;ng hoặc người đại diện hợp ph&aacute;p của Kh&aacute;ch h&agrave;ng; v&agrave;/hoặc (b) được gửi theo dịch vụ bưu ch&iacute;nh c&oacute; bảo đảm theo x&aacute;c nhận của cơ quan bưu ch&iacute;nh; v&agrave;/hoặc (c) v&agrave;o ng&agrave;y được ni&ecirc;m yết ch&iacute;nh thức tr&ecirc;n Internet Banking; v&agrave;/hoặc (d) gửi qua địa chỉ email Kh&aacute;ch h&agrave;ng đ&atilde; đăng k&yacute; tr&ecirc;n Internet Banking.</p>
<p style="text-align:justify">3. Mọi th&ocirc;ng tin giải đ&aacute;p, Qu&yacute; kh&aacute;ch li&ecirc;n hệ tới Bộ phận chăm s&oacute;c kh&aacute;ch h&agrave;ng:</p>
<p style="text-align:justify">a. Hotlines: 1800 599 999</p>
<p style="text-align:justify">b. Email: CSKHCaNhan@msb.com.vn</p>
<p style="text-align:justify">4. Việc tiếp nhận, phối hợp xử l&yacute; c&aacute;c tra so&aacute;t, khiếu nại của Kh&aacute;ch h&agrave;ng thực hiện theo quy định chi tiết tại bản Điều khoản điều kiện giao dịch chung dịch vụ ng&acirc;n h&agrave;ng điện tử.</p>
<p style="text-align:justify">Điều 15. Điều Khoản Ph&ograve;ng Chống Tham Nhũng V&agrave; Tu&acirc;n Thủ Ph&aacute;p Luật</p>
<p style="text-align:justify">Trong qu&aacute; tr&igrave;nh cung cấp v&agrave; sử dụng dịch vụ, MSB v&agrave; Kh&aacute;ch h&agrave;ng cam kết lu&ocirc;n tu&acirc;n thủ ph&aacute;p luật, gồm cả Luật Ph&ograve;ng, chống tham nhũng (như kh&ocirc;ng đưa/nhận hối lộ, tham &ocirc;, tham nhũng); chịu ho&agrave;n to&agrave;n tr&aacute;ch nhiệm trước ph&aacute;p luật v&agrave; bồi thường thiệt hại cho c&aacute;c B&ecirc;n li&ecirc;n quan (nếu c&oacute;) khi vi phạm cam kết n&agrave;y.</p>
<p style="text-align:justify">Điều 16. Luật Điều Chỉnh V&agrave; Giải Quyết Tranh Chấp.</p>
<p style="text-align:justify">1. Bản Điều khoản điều kiện giao dịch n&agrave;y được điều chỉnh bởi ph&aacute;p luật Việt Nam.&nbsp;</p>
<p style="text-align:justify">2. Trong trường hợp c&oacute; tranh chấp xảy ra, hai B&ecirc;n sẽ c&ugrave;ng nhau giải quyết tr&ecirc;n tinh thần thương lượng hợp t&aacute;c để c&ugrave;ng nhau t&igrave;m ra hướng giải quyết c&oacute; lợi cho cả hai B&ecirc;n. Nếu kh&ocirc;ng thể thương lượng v&agrave; giải quyết tranh chấp được trong thời hạn ba mươi (30) ng&agrave;y kể từ ng&agrave;y ph&aacute;t sinh tranh chấp th&igrave; một trong c&aacute;c b&ecirc;n c&oacute; quyền đưa tranh chấp ra giải quyết bằng phương thức trọng t&agrave;i tại Trung t&acirc;m Trọng t&agrave;i Quốc tế Việt Nam (VIAC) b&ecirc;n cạnh Ph&ograve;ng Thương mại v&agrave; C&ocirc;ng nghiệp Việt Nam theo Quy tắc tố tụng trọng t&agrave;i của Trung t&acirc;m n&agrave;y với:</p>
<p style="text-align:justify">a) Số lượng trọng t&agrave;i vi&ecirc;n l&agrave; ba (03);</p>
<p style="text-align:justify">b) Địa điểm trọng t&agrave;i l&agrave; th&agrave;nh phố H&agrave; Nội, Việt Nam;</p>
<p style="text-align:justify">c) Ng&ocirc;n ngữ trọng t&agrave;i l&agrave; tiếng Việt.</p>
<p style="text-align:justify">3. B&ecirc;n thua kiện c&oacute; nghĩa vụ thanh to&aacute;n c&aacute;c khoản ph&iacute;, lệ ph&iacute; li&ecirc;n quan đến thủ tục tố tụng, bao gồm cả chi ph&iacute; thu&ecirc; luật sư (nếu c&oacute;) m&agrave; B&ecirc;n kia phải bỏ ra để giải quyết vụ kiện.</p>
  `;

  const dispatch = useDispatch()

  const { sendOTPRegister, sendOTPOnly, sendOTPOnlyError } = useSelector((state) => state.overdraft)
  const [checked, setCheck] = useState(false)
  const [loading, setLoading] = useState(false)
  const [isSetup, setIsSetup] = useState(false)

  const onVerify = () => {
    const body = {
      ...sendOTPRegister
    }
    setLoading(true)
    setIsSetup(true)
    dispatch(odSavingOperations.sendOtpOnly(body))
  }

  React.useEffect(() => {
    setLoading(false)
    if (isSetup && sendOTPOnly) {
      setIsSetup(false)
      Navigation.push('CreateODVerify', { title: 'CreateODVerify' })
    }
  }, [sendOTPOnly])

  React.useEffect(() => {
    setLoading(false)
    setIsSetup(false)
  }, [sendOTPOnlyError])
  // I18n.t('overdraft.fromOnlineSaving.conditionTitle').toUpperCase()

  
  return (
    <Fragment>
      <Topbar subTitle={I18n.t('overdraft.fromOnlineSaving.openScreenTitle')} background={Colors.mainBg} title={I18n.t('overdraft.fromOnlineSaving.title')} />
      <View style={[Helpers.fill, styles.container]}>
        <ScrollView
          style={Helpers.fullWidth}
          showsVerticalScrollIndicator={false}
          extraHeight={300}
          keyboardShouldPersistTaps="handled"
        >
          <View style={styles.titleContainer}>
            <Text style={styles.title}>BẢN ĐIỀU KHOẢN ĐIỀU KIỆN GIAO DỊCH CHUNG CHO VIỆC CẤP HẠN MỨC THẤU CHI BẰNG PHƯƠNG TIỆN ĐIỆN TỬ BẢO ĐẢM BẰNG TIỀN GỬI TIẾT KIỆM ONLINE</Text>
          </View>
          <View style={[styles.line, { marginBottom: Metrics.small }]} />

          <HTML
            ignoredStyles={[...IGNORED_TAGS, 'font-family']}
            baseFontStyle={{
              fontSize: Utils.getRatioDimension(14),
            }}
            source={{ html: htmlContent }}
            // html={htmlContent}
          />
        </ScrollView>
        <View style={styles.line} />
        <Radio
          size={Utils.getRatioDimension(18)}
          style={[styles.checkBox]}
          textStyle={styles.textCheckBox}
          text={I18n.t('overdraft.text_condition')}
          checked={checked}
          onPress={() => {
            setCheck(!checked)
          }}
        />
      </View>

      <ConfirmButton
        onPress={() => onVerify()}
        disabled={!checked}
        color={!checked ? Colors.gray4 : Colors.primary2}
      />
      <Loader modalVisible={loading} />
    </Fragment>
  )
}

export default CreateODConfirm
